local AFInAppEvents = {
	--[[
	 * Event Type
	]]
	LEVEL_ACHIEVED = "af_level_achieved",
	ADD_PAYMENT_INFO = "af_add_payment_info",
	ADD_TO_CART = "af_add_to_cart",
	ADD_TO_WISH_LIST = "af_add_to_wishlist",
	COMPLETE_REGISTRATION = "af_complete_registration",
	TUTORIAL_COMPLETION = "af_tutorial_completion",
	INITIATED_CHECKOUT = "af_initiated_checkout",
	PURCHASE = "af_purchase",
	RATE = "af_rate",
	SEARCH = "af_search",
	SPENT_CREDIT = "af_spent_credits",
	ACHIEVEMENT_UNLOCKED = "af_achievement_unlocked",
	CONTENT_VIEW = "af_content_view",
	TRAVEL_BOOKING = "af_travel_booking",
	SHARE = "af_share",
	INVITE = "af_invite",
	LOGIN = "af_login",
	RE_ENGAGE = "af_re_engage",
	UPDATE = "af_update",
	OPENED_FROM_PUSH_NOTIFICATION = "af_opened_from_push_notification",
	LOCATION_CHANGED = "af_location_changed",
	LOCATION_COORDINATES = "af_location_coordinates",
	ORDER_ID = "af_order_id",
	--[[
	 * Event Parameter Name
	]]
	LEVEL = "af_level",
	SCORE = "af_score",
	SUCCESS = "af_success",
	PRICE = "af_price",
	CONTENT_TYPE = "af_content_type",
	CONTENT_ID = "af_content_id",
	CONTENT_LIST = "af_content_list",
	CURRENCY = "af_currency",
	QUANTITY = "af_quantity",
	CHANNEL = "af_channel",
	REGSITRATION_METHOD = "af_registration_method",
	PAYMENT_INFO_AVAILIBLE = "af_payment_info_available",
	MAX_RATING_VALUE = "af_max_rating_value",
	RATING_VALUE = "af_rating_value",
	SEARCH_STRING = "af_search_string",
	DATE_A = "af_date_a",
	DATE_B = "af_date_b",
	DESTINATION_A = "af_destination_a",
	DESTINATION_B = "af_destination_b",
	DESCRIPTION = "af_description",
	CLASS = "af_class",
	EVENT_START = "af_event_start",
	EVENT_END = "af_event_end",
	LATITUDE = "af_lat",
	LONGTITUDE = "af_long",
	CUSTOMER_USER_ID = "af_customer_user_id",
	VALIDATED = "af_validated",
	REVENUE = "af_revenue",
	RECEIPT_ID = "af_receipt_id",
	PARAM_1 = "af_param_1",
	PARAM_2 = "af_param_2",
	PARAM_3 = "af_param_3",
	PARAM_4 = "af_param_4",
	PARAM_5 = "af_param_5",
	PARAM_6 = "af_param_6",
	PARAM_7 = "af_param_7",
	PARAM_8 = "af_param_8",
	PARAM_9 = "af_param_9",
	PARAM_10 = "af_param_10",
	REGISTER_TYPE = "af_register_type"
}

return AFInAppEvents
