---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mayd.
--- DateTime: 2020/6/3 17:53
---

local CC = require("CC")

local CaptureScreenShareViewCtr = CC.class2("CaptureScreenShareViewCtr")

function CaptureScreenShareViewCtr:ctor(view, param)
    
    self.param = param

    self.view = view
end

function CaptureScreenShareViewCtr:OnCreate()
    self:RegisterEvent()
end

function CaptureScreenShareViewCtr:RegisterEvent()
    
end

function CaptureScreenShareViewCtr:unRegisterEvent()
    
end

--分享成功回调
function CaptureScreenShareViewCtr:OnUrlOpenApplicationCallback(data)
    CC.ViewManager.ShowMessageBox("分享成功")
end

function CaptureScreenShareViewCtr:Destroy()
    self:unRegisterEvent()
end

return CaptureScreenShareViewCtr