local ChannelSwitch={	
	{
		Id = 0,
		name = 'comments',
		bHasGuestLogin = '游客登录',
		bHasChannelLogin = '渠道登录',
		bHasAppleLogin = '苹果登录',
		nThirdPartner = '第三方类型',
		bHallPop = '大厅弹窗',
		bHasGift = '礼包',
		bHasFreeChips = '免费筹码',
		bHasActivity = '活动',
		bHasRealStore = '实物商城',
		bCheckLoadingImg = 'loading图切换',
		tActiveTabShow = '大厅图标显示',
		tActiveTabNotShow = '大厅图标隐藏',
		bHasVip = 'VIP',
		bShowMol = 'Mol支付',
		bShowWeekRank = '周排行',
		bShowTotalRank = '总排行',
		bShowSendChip = '赠送相关',
		bHasGuide = '新手引导',
		bHasRelief = '救济金',
		bHasActive = '活动以及广告页',
		bHasMiniHall = '小厅'
	},
	{
		Id = 1,
		name = 'android',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 2,
		name = 'ios',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = true,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 3,
		name = 'pc',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 10000,
		name = 'ios_Thai_Private',
		bHasGuestLogin = false,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = false,
		bHasFreeChips = true,
		bHasActivity = false,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 10002,
		name = 'ios_Thai_Rat',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = true,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 10003,
		name = 'ios_Thai_Taiwan',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = true,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 20001,
		name = 'android_Thai_Google',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 20002,
		name = 'android_Thai_Oppo',
		bHasGuestLogin = false,
		bHasChannelLogin = true,
		bHasAppleLogin = false,
		nThirdPartner = 1,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 20003,
		name = 'android_Thai_Vivo',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 1,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 20004,
		name = 'android_Thai_Googlebc',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 20101,
		name = 'android_Vietnam_Google',
		bHasGuestLogin = false,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = true,
		bHasFreeChips = true,
		bHasActivity = true,
		bHasRealStore = true,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			
		},
		bHasVip = true,
		bShowMol = true,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = true,
		bHasGuide = true,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = true
	},
	{
		Id = 19999,
		name = 'ios_Trail',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = true,
		nThirdPartner = 0,
		bHallPop = true,
		bHasGift = false,
		bHasFreeChips = false,
		bHasActivity = true,
		bHasRealStore = false,
		bCheckLoadingImg = false,
		tActiveTabShow = {			1
		},
		tActiveTabNotShow = {			2,3,4,6,7,8,9
		},
		bHasVip = false,
		bShowMol = true,
		bShowWeekRank = false,
		bShowTotalRank = false,
		bShowSendChip = false,
		bHasGuide = false,
		bHasRelief = false,
		bHasActive = false,
		bHasMiniHall = false
	},
	{
		Id = 29999,
		name = 'android_Trail',
		bHasGuestLogin = true,
		bHasChannelLogin = false,
		bHasAppleLogin = false,
		nThirdPartner = 0,
		bHallPop = false,
		bHasGift = false,
		bHasFreeChips = false,
		bHasActivity = true,
		bHasRealStore = false,
		bCheckLoadingImg = true,
		tActiveTabShow = {			
		},
		tActiveTabNotShow = {			2,3,4,6
		},
		bHasVip = false,
		bShowMol = false,
		bShowWeekRank = true,
		bShowTotalRank = true,
		bShowSendChip = false,
		bHasGuide = false,
		bHasRelief = true,
		bHasActive = true,
		bHasMiniHall = false
	}
}
return ChannelSwitch