-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local pb = {}
local descriptor = {}

descriptor.QUEUEDATAREQ = protobuf.Descriptor();
descriptor.QUEUEDATARESP = protobuf.Descriptor();
descriptor.QUEUEDATARESP_QUEUETIME_FIELD = protobuf.FieldDescriptor();
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD = protobuf.FieldDescriptor();
descriptor.QUEUEDATARESP_RANK_FIELD = protobuf.FieldDescriptor();
descriptor.QUEUEHEARTBEATREQ = protobuf.Descriptor();
descriptor.PUSHQUEUEREQ = protobuf.Descriptor();

descriptor.QUEUEDATAREQ.name = "QueueDataReq"
descriptor.QUEUEDATAREQ.full_name = ".VK.Proto.QueueDataReq"
descriptor.QUEUEDATAREQ.nested_types = {}
descriptor.QUEUEDATAREQ.enum_types = {}
descriptor.QUEUEDATAREQ.fields = {}
descriptor.QUEUEDATAREQ.is_extendable = false
descriptor.QUEUEDATAREQ.extensions = {}
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.name = "QueueTime"
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.full_name = ".VK.Proto.QueueDataResp.QueueTime"
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.number = 1
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.index = 0
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.label = 1
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.has_default_value = false
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.default_value = 0
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.type = 3
descriptor.QUEUEDATARESP_QUEUETIME_FIELD.cpp_type = 2

descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.name = "GameUserNum"
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.full_name = ".VK.Proto.QueueDataResp.GameUserNum"
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.number = 2
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.index = 1
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.label = 1
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.has_default_value = false
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.default_value = 0
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.type = 3
descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD.cpp_type = 2

descriptor.QUEUEDATARESP_RANK_FIELD.name = "Rank"
descriptor.QUEUEDATARESP_RANK_FIELD.full_name = ".VK.Proto.QueueDataResp.Rank"
descriptor.QUEUEDATARESP_RANK_FIELD.number = 3
descriptor.QUEUEDATARESP_RANK_FIELD.index = 2
descriptor.QUEUEDATARESP_RANK_FIELD.label = 1
descriptor.QUEUEDATARESP_RANK_FIELD.has_default_value = false
descriptor.QUEUEDATARESP_RANK_FIELD.default_value = 0
descriptor.QUEUEDATARESP_RANK_FIELD.type = 3
descriptor.QUEUEDATARESP_RANK_FIELD.cpp_type = 2

descriptor.QUEUEDATARESP.name = "QueueDataResp"
descriptor.QUEUEDATARESP.full_name = ".VK.Proto.QueueDataResp"
descriptor.QUEUEDATARESP.nested_types = {}
descriptor.QUEUEDATARESP.enum_types = {}
descriptor.QUEUEDATARESP.fields = {descriptor.QUEUEDATARESP_QUEUETIME_FIELD, descriptor.QUEUEDATARESP_GAMEUSERNUM_FIELD, descriptor.QUEUEDATARESP_RANK_FIELD}
descriptor.QUEUEDATARESP.is_extendable = false
descriptor.QUEUEDATARESP.extensions = {}
descriptor.QUEUEHEARTBEATREQ.name = "QueueHeartbeatReq"
descriptor.QUEUEHEARTBEATREQ.full_name = ".VK.Proto.QueueHeartbeatReq"
descriptor.QUEUEHEARTBEATREQ.nested_types = {}
descriptor.QUEUEHEARTBEATREQ.enum_types = {}
descriptor.QUEUEHEARTBEATREQ.fields = {}
descriptor.QUEUEHEARTBEATREQ.is_extendable = false
descriptor.QUEUEHEARTBEATREQ.extensions = {}
descriptor.PUSHQUEUEREQ.name = "PushQueueReq"
descriptor.PUSHQUEUEREQ.full_name = ".VK.Proto.PushQueueReq"
descriptor.PUSHQUEUEREQ.nested_types = {}
descriptor.PUSHQUEUEREQ.enum_types = {}
descriptor.PUSHQUEUEREQ.fields = {}
descriptor.PUSHQUEUEREQ.is_extendable = false
descriptor.PUSHQUEUEREQ.extensions = {}


pb.QUEUEDATAREQ = descriptor.QUEUEDATAREQ;
pb.QUEUEDATARESP = descriptor.QUEUEDATARESP;
pb.QUEUEHEARTBEATREQ = descriptor.QUEUEHEARTBEATREQ;
pb.PUSHQUEUEREQ = descriptor.PUSHQUEUEREQ;

pb.PushQueueReq = protobuf.Message(descriptor.PUSHQUEUEREQ)
pb.QueueDataReq = protobuf.Message(descriptor.QUEUEDATAREQ)
pb.QueueDataResp = protobuf.Message(descriptor.QUEUEDATARESP)
pb.QueueHeartbeatReq = protobuf.Message(descriptor.QUEUEHEARTBEATREQ)

return pb