-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf/protobuf"
local pb = {}
local descriptor = {}

descriptor.EXCHAGECHMTOMINI = protobuf.Descriptor();
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD = protobuf.FieldDescriptor();
descriptor.EXCHANGEMINITOCHM = protobuf.Descriptor();
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD = protobuf.FieldDescriptor();
descriptor.MININOTIFY = protobuf.Descriptor();
descriptor.MININOTIFY_GAMEID_FIELD = protobuf.FieldDescriptor();
descriptor.MININOTIFY_JSON_FIELD = protobuf.FieldDescriptor();
descriptor.MININOTIFY_TIMESTAMP_FIELD = protobuf.FieldDescriptor();
descriptor.LOADMINISTATUSRESP = protobuf.Descriptor();
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD = protobuf.FieldDescriptor();
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD = protobuf.FieldDescriptor();

descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.name = "Amount"
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.full_name = ".VK.Proto.ExchageChmToMini.Amount"
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.number = 1
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.index = 0
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.label = 2
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.has_default_value = false
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.default_value = 0
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.type = 3
descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD.cpp_type = 2

descriptor.EXCHAGECHMTOMINI.name = "ExchageChmToMini"
descriptor.EXCHAGECHMTOMINI.full_name = ".VK.Proto.ExchageChmToMini"
descriptor.EXCHAGECHMTOMINI.nested_types = {}
descriptor.EXCHAGECHMTOMINI.enum_types = {}
descriptor.EXCHAGECHMTOMINI.fields = {descriptor.EXCHAGECHMTOMINI_AMOUNT_FIELD}
descriptor.EXCHAGECHMTOMINI.is_extendable = false
descriptor.EXCHAGECHMTOMINI.extensions = {}
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.name = "Amount"
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.full_name = ".VK.Proto.ExchangeMiniToChm.Amount"
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.number = 1
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.index = 0
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.label = 2
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.has_default_value = false
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.default_value = 0
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.type = 3
descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD.cpp_type = 2

descriptor.EXCHANGEMINITOCHM.name = "ExchangeMiniToChm"
descriptor.EXCHANGEMINITOCHM.full_name = ".VK.Proto.ExchangeMiniToChm"
descriptor.EXCHANGEMINITOCHM.nested_types = {}
descriptor.EXCHANGEMINITOCHM.enum_types = {}
descriptor.EXCHANGEMINITOCHM.fields = {descriptor.EXCHANGEMINITOCHM_AMOUNT_FIELD}
descriptor.EXCHANGEMINITOCHM.is_extendable = false
descriptor.EXCHANGEMINITOCHM.extensions = {}
descriptor.MININOTIFY_GAMEID_FIELD.name = "GameID"
descriptor.MININOTIFY_GAMEID_FIELD.full_name = ".VK.Proto.MiniNotify.GameID"
descriptor.MININOTIFY_GAMEID_FIELD.number = 1
descriptor.MININOTIFY_GAMEID_FIELD.index = 0
descriptor.MININOTIFY_GAMEID_FIELD.label = 2
descriptor.MININOTIFY_GAMEID_FIELD.has_default_value = false
descriptor.MININOTIFY_GAMEID_FIELD.default_value = 0
descriptor.MININOTIFY_GAMEID_FIELD.type = 5
descriptor.MININOTIFY_GAMEID_FIELD.cpp_type = 1

descriptor.MININOTIFY_JSON_FIELD.name = "Json"
descriptor.MININOTIFY_JSON_FIELD.full_name = ".VK.Proto.MiniNotify.Json"
descriptor.MININOTIFY_JSON_FIELD.number = 2
descriptor.MININOTIFY_JSON_FIELD.index = 1
descriptor.MININOTIFY_JSON_FIELD.label = 1
descriptor.MININOTIFY_JSON_FIELD.has_default_value = false
descriptor.MININOTIFY_JSON_FIELD.default_value = ""
descriptor.MININOTIFY_JSON_FIELD.type = 9
descriptor.MININOTIFY_JSON_FIELD.cpp_type = 9

descriptor.MININOTIFY_TIMESTAMP_FIELD.name = "TimeStamp"
descriptor.MININOTIFY_TIMESTAMP_FIELD.full_name = ".VK.Proto.MiniNotify.TimeStamp"
descriptor.MININOTIFY_TIMESTAMP_FIELD.number = 3
descriptor.MININOTIFY_TIMESTAMP_FIELD.index = 2
descriptor.MININOTIFY_TIMESTAMP_FIELD.label = 1
descriptor.MININOTIFY_TIMESTAMP_FIELD.has_default_value = false
descriptor.MININOTIFY_TIMESTAMP_FIELD.default_value = 0
descriptor.MININOTIFY_TIMESTAMP_FIELD.type = 3
descriptor.MININOTIFY_TIMESTAMP_FIELD.cpp_type = 2

descriptor.MININOTIFY.name = "MiniNotify"
descriptor.MININOTIFY.full_name = ".VK.Proto.MiniNotify"
descriptor.MININOTIFY.nested_types = {}
descriptor.MININOTIFY.enum_types = {}
descriptor.MININOTIFY.fields = {descriptor.MININOTIFY_GAMEID_FIELD, descriptor.MININOTIFY_JSON_FIELD, descriptor.MININOTIFY_TIMESTAMP_FIELD}
descriptor.MININOTIFY.is_extendable = false
descriptor.MININOTIFY.extensions = {}
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.name = "Items"
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.full_name = ".VK.Proto.LoadMiniStatusResp.Items"
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.number = 1
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.index = 0
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.label = 3
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.has_default_value = false
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.default_value = {}
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.message_type = descriptor.MININOTIFY
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.type = 11
descriptor.LOADMINISTATUSRESP_ITEMS_FIELD.cpp_type = 10

descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.name = "TimeStamp"
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.full_name = ".VK.Proto.LoadMiniStatusResp.TimeStamp"
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.number = 2
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.index = 1
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.label = 1
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.has_default_value = false
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.default_value = 0
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.type = 3
descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD.cpp_type = 2

descriptor.LOADMINISTATUSRESP.name = "LoadMiniStatusResp"
descriptor.LOADMINISTATUSRESP.full_name = ".VK.Proto.LoadMiniStatusResp"
descriptor.LOADMINISTATUSRESP.nested_types = {}
descriptor.LOADMINISTATUSRESP.enum_types = {}
descriptor.LOADMINISTATUSRESP.fields = {descriptor.LOADMINISTATUSRESP_ITEMS_FIELD, descriptor.LOADMINISTATUSRESP_TIMESTAMP_FIELD}
descriptor.LOADMINISTATUSRESP.is_extendable = false
descriptor.LOADMINISTATUSRESP.extensions = {}


pb.EXCHAGECHMTOMINI = descriptor.EXCHAGECHMTOMINI;
pb.EXCHANGEMINITOCHM = descriptor.EXCHANGEMINITOCHM;
pb.MININOTIFY = descriptor.MININOTIFY;
pb.LOADMINISTATUSRESP = descriptor.LOADMINISTATUSRESP;

pb.ExchageChmToMini = protobuf.Message(descriptor.EXCHAGECHMTOMINI)
pb.ExchangeMiniToChm = protobuf.Message(descriptor.EXCHANGEMINITOCHM)
pb.LoadMiniStatusResp = protobuf.Message(descriptor.LOADMINISTATUSRESP)
pb.MiniNotify = protobuf.Message(descriptor.MININOTIFY)

return pb