local lan =
{
	btn_NewInvitation = "新手玩家赚钱",
	btn_Invitation = "百亿补贴",
	btn_Revenue = "我的收益",
	btn_Share = "我的推广码",
	btn_Grades = "我的等级",
	btn_Rank = "推广赚钱榜",
	e0 = "总收益",
	e1 = "游戏收益",
	e2 = "推广收益",
	e3 = "赠送收益",

	btnFB = "FaceBook",
	btnLine = "Line",
	btnOther = "Other",
	codelabel = "新手邀请码",
	shareTips = "输入该号码，马上获得免费10W金币",

	sharetitle = "分享",
	sharecopylink = "复制链接",
	sharecopysucc = "复制成功",

	ruletitle = "规则说明",
	rulemaintext = "恭喜您成为高V！快去完成推广人物吧！！",
	rulecontent1 = "每次你推广你的朋友的游戏，你会得到更多的利润，玩游戏，你赚的利润更多！",
	rulecontent2 = "每次你推广朋友时，当你达到游戏的活动级别，你会有利可图。能推广的朋友就多，利润也越丰厚！",
	rulecontent3 = "每次朋友利用赠送功能宣传朋友并收到赠送时，您都会从发送赠送中获利。赠送的筹码越多，活动的利润就更多！",

	earningstitle = "收益查询",
	earningstotal0 = "累计领取总收益：",
	earningstotal1 = "累计领取游戏收益：",
	earningstotal2 = "累计领取推广收益：",
	earningstotal3 = "累计领取赠送收益",
	earningstime = "领取时间",
	earningsnum = "领取数量",
	earningstype = "收益类型",

	generalizetitle = "推广历史",
	generalizetotal = "累计推广总人数：",
	generalizeyear = "%d年",
	generalizemonth = {"1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"},
	generalizenum = "推广人数：",

	juniortitle = "下级信息",
	juniornum = "下级人数：",

	juniorname = "姓名",
	juniortime = "时间",

	agentbtntips1 = "ผลกำไรส่งชิป",
	agentbtntips2 = "ผลกำไรเกม",
	agentbtntips3 = "ผลกำไรโปรโมท",
	agentbtntips9 = "推广好友",
	timeout = "请求超时，请重试",

	receiveTip = "您有奖励未领",
	taskTitle = "推广任务",
	taskName = "任务名称",
	taskReward = "奖励",
	taskCompletion = "伙伴完成度",
	taskEarn = "收益",
	taskUndone = "暂无好友完成",
	taskLook = "<u>查看更多</u>",
	taskGet = "领取",
	taskShare = "通知伙伴完成任务",
	totalEarn = "待领取总收益:",
	btnAll = "一键领取",
	taskTip = "推广任务收益如48小时内\n未手动领取系统则自动发放\n审核期不自动派奖\n推广任务须在72小时内完成",
	taskTipText = "只有绑定第三方账号的下级才可完成任务",
	agentTask = {
		[1] = "流水达到30000",
		[2] = "累计充值29THB",
		[3] = "累计充值300THB",
		-- [1] = "新伙伴注册\n(非游客)",
		-- [2] = "绑定OTP\n(需完成上述任务)",
		-- [3] = "伙伴参与游戏\n(需完成上述任务)",
		-- [4] = "累计充值29THB",
	},

	UnderlingTitle = {
        -- [1] = "流水达到30000",
		-- [2] = "累计充值29THB",
		-- [3] = "累计充值500THB",
		[1] = "新伙伴注册",
		[2] = "绑定OTP",
		[3] = "伙伴参与游戏",
		[4] = "累计充值29THB",
		[5] = "流水达到30000",
		[6] = "累计充值29THB",
		[7] = "累计充值300THB",
    },
	UnderlingNone = "当前未有记录",
	UnderlingSave = "记录仅保存7天",
	UnderlingShow = "每页仅展示100条记录",
	UnderlingTotalNum = "共%s人完成",
	UnderlingId = "账号",
	UnderlingVip= "VIP等级",
	UnderlingEarn = "收益",
	UnderlingState = "领取状态",
	UnderlingTime = "完成时间",
	UnderlingTick = "未领取",

	Placeholder = "请输入...",
	vip = "VIP",

	earnViewDes = "游客账号不计算分成奖励，只有成功绑定第三方账号或手机才可计算分成。",
	proxyTitle = "推广码",
	proxyDesText = "输入好友推广码，立即获得<color=#FFF900>100,000</color>筹码！",
	proxyBtnText = "提交",
	proxyTipText = "推广码奖励会发送至邮箱，请注意查收",
	proxyBlindText = "您已被推广",
	notice_proxy_fail = "绑定失败，系统检测设备异常",
	timeout_tip = "请求超时，请重试",
	guestBlindTip = "当前是游客账号不能获得100000筹码奖励，绑定第三方账号或手机后可获得",
	invitationPlay = "邀请TA助力",
	invitationTip = "成功助力好友数：%s人，奖励请在【我的收益】查收",
	invitationAward = "好友成功助力，也可免费领取 <size=28><color=#BDF8FF>100,000</color></size> 筹码奖励",
	invitationBtnGuide = "领取奖励",
	invitationGuideText1 = "恭喜您已邀请7位好友助力",
	invitationGuideText2 = "现可前往【我的收益】领取礼券奖励。\n集齐14000礼券可在【实物商城】兑换50点卡哦！",
	invitationGuideBtn = "立即领取",
	InvitationText = "邀请%s个人送",

	Marquee_1 = "<color=#FFFFFFFF>恭喜<color=#13FF00FF>%s</color>通过邀请好友免费获得了<color=#00FFFFFF>%s</color>礼券<color=#FBFF00FF>%s</color>筹码</color>",
	Marquee_2 = "<color=#FFFFFFFF>恭喜<color=#13FF00FF>%s</color>通过邀请好友免费获得了<color=#FBFF00FF>%s</color>筹码</color>",
	Marquee_3 = "<color=#FFFFFFFF>恭喜<color=#13FF00FF>%s</color>通过邀请好友免费获得了<color=#00FFFFFF>%s</color>礼券</color>",
	Marquee_4 = "<color=#FFFFFFFF>Oh My God, 恭喜<color=#13FF00FF>%s</color>通过邀请好友免费赚到了<color=#00FFFFFF>%s</color>礼券<color=#FBFF00FF>%s</color>筹码</color>",
	Marquee_5 = "<color=#FFFFFFFF>Oh My God, 恭喜<color=#13FF00FF>%s</color>通过邀请好友免费赚到了<color=#FBFF00FF>%s</color>筹码</color>",
	Marquee_6 = "<color=#FFFFFFFF>Oh My God, 恭喜<color=#13FF00FF>%s</color>通过邀请好友免费赚到了<color=#00FFFFFF>%s</color>礼券</color>",
	freeGet = "邀请好友",
	totalEran = "累计总收益",
	Invite = "已邀请:",
	InviteSucced = "昨日活跃下级:",
	noneEarn = "当前暂无奖励可领取，马上邀请好友获得奖励！",
	TradeEarn = "赠送收益",
	ShareEarn = "游戏收益",
	NewerEarn = "人头收益",
	ShareEarnTip = "您的下级玩家在游戏中消耗筹码\n我们将把部分筹码奖励给您",
	TradeEarnTip = "您的下级玩家赠送时\n我们将把部分筹码奖励给您",

	ranking = "名次",
	rankName = "玩家信息",
	rankPeople = "周推广人数",
	rankAward = "排行奖励",
	rankPeopleTip = "仅算人头收益中完成第一个任务的玩家数量\n下级推广的有效人数不会累计！",
	rankEmpty = "暂无数据",
	rankMy = "我的排行:",
	rankRequire = "至少要推广成功50人才可以获得奖励",
	rankExplain = "每周一0点刷新排行榜\n排名信息,每5分钟更新一次。",
	rankFreeTaxTip = "自动激活，激活后赠送免交易税一周",
	rankLast = "上周排名",
	rankCur = "本周排名",

	myGradesTip = "每周任务若未完成则将会降一级！",
	myGradesBtnGet = "立即分享",
	myGradesReward = "奖励",
	myGradesNeedPeople = "本周推广 %s人",
	myGradesPeopleTip = "仅算人头收益中完成第一个任务的玩家数量\n下级推广的有效人数也会全部累计！",
	myGradesCountDown = "每周任务:",
	myGradesTime = "剩余:%s天%s小时",
	myGradesCurLevel = "当前等级：",
	myGradesNextLevel = "下个等级：",
	myGradesSend = "赠送收益特权 %s",
	myGradesDivide = "流水分成比例 %s",
	myGradesTable = "桌费分成比例 %s",
	myGradesAnimTip = "根据您目前的推广人数，经鉴定，您的段位为%s！ 立即前往查看段位权益",
	myGradesAnimUpgrade = "恭喜您完成%s每周任务，晋升到%s段位。获得%s宝箱奖励，请去邮箱查收。",
	myGradesAnimDegrade = "您本周%s任务未完成，下降到%s段位。",
	myGradesBtn = "确定",
	myGradesList = {[1] = "黑铁", [2] = "青铜", [3] = "白银", [4] = "黄金", [5] = "钻石", [6] = "王者"},
	myGradesRule1 = "1.完成周任务下周结算即可享受相应的等级特权，周任务宝箱只发送最高奖励，不累计发送。",
	myGradesRule2 = "2.有效人数仅计算绑定第三方且游戏流水达30000的下级玩家（3天内完成）",
	myGradesRule3 = "3.禁止恶意作弊行为，如有发现，立即冻结。",
	myGradesRuleLevel = "等级",
	myGradesRuleSend = "赠送分成",
	myGradesRuleDivide = "流水分成",
	myGradesRuleTable = "桌费分成",
	myGradesLock = "解锁收益",

	shareGuide = "分享之后，立刻兑换20THB 电子钱包。",
	auditTip = "你的账号处于审核期，请等待审核通过",
	auditPeriod = "你的账号处于审核期",
	auditTime = "解锁获取收益时间：%s",
	auditRankAward = "若您的账号处于审核期\n则无法领取本周排名奖励\n获奖玩家请审核通过后\n主动联系客服领取排名奖励",

	limit_topText = "剩余时间: ",
	limit_LTitle = "邀请2人送",
	limit_RTitle = "20THB",
	tips_Text = "全服累计领取 ：%s THB",
	guide_Text = "升级vip1即可立即领取红包奖励哦！",
}

return lan