local lan = {
    Time = "活动时间：26.08.2022 - 04.09.2022",
    OnceBtn = "抽一次",
    MoreBtn = "抽十次",
    MoreTips = "礼票十连抽可额外获得【巫师帽】*1",
    VIPNotEnough = "您的每日筹码抽奖上限次数为2，升级vip，畅享抽奖无上限！",
    ChipNotEnough = "当前筹码不足，无法参与抽奖",
    TicketNotEnough = "提示：当前礼票不足，无法参与抽奖",
    RewardRecord = "恭喜【%s】获得超级大奖%s",
    FreeBtn = "免费次数",
    ShareText = "每日分享%s",
    OnlineText = "在线20分钟<color=#32D83AFF>+1</color>",
    ShareContent = "ROYAL CASINO万圣节扭蛋狂欢派对开始啦！快来和我一起狂欢吧~ 里面不单有丰富超级大奖，还有超多福利等着你哦~",
    FreeTimsNotEnough = "免费次数不足",
    -- SnowNotEnough = "当前圣诞雪花不足，无法参与抽奖",
    SnowNotEnough = "当前幸运星不足，无法参与抽奖",
    notLottety = "很抱歉，未中奖",
    btnPreview = "预览全部奖励",

    explainTitle = "活动说明",
    explainContent = "\n本活动是额外奖励活动，活动只提供特别奖品，没有金币产出，有概率不中奖",
    closeTip = "点击任意空白区域关闭",
    coinNotEnough = "当前扭蛋币不足，请前往其他活动内获取",
    -- coinNotEnough = "当前幸运星不足，请前往其他活动内获取",
    toggleBig = "中奖幸运儿",
    toggleMy = "我的中奖记录",
    toggleCount = "抽奖次数",
    countText = "次数",
    activity1 = {tag = "95%选择", name = "充值奖励"},
    activity2 = {tag = "性价比", name = "登录好礼"},
    activity3 = {tag = "性价比", name = "假日狂欢"},
    activity4 = {tag = "免费获得", name = "每日抽奖"},
    egg1 = "普通扭蛋",
    egg2 = "黄金扭蛋",
    egg3 = "钻石扭蛋",
    activityTip = "活动暂未开启，敬请期待",
}

return lan