local lan =
{
	system = "ระบบ",
	public = "ล็อบบี้",
	private = "แชทส่วนตัว",
	placeholder = "พิมพ์ข้อความแชท",
	privateBtn = "ส่ง",
	privateLabel = "ขณะนี้ไม่มีข้อความแชทส่วนตัว",
	system_name = "ข้อความระบบ",
	send_tip_front = "ส่งข้อความจะต้องใช้",
	send_tip_noCoin = "ชิป ตอนนี้ไม่เพียงพอ",
	send_tip_coin = "ชิป",
	send_tip_horn = "โทรโข่ง",
	send_tip_noHorn = "โทรโข่ง ตอนนี้ชิปไม่เพียงพอ",
	send_btn_shop = "ซื้อ",
	send_btn_close = "ปิด",
	chat_second = "%dวินาที",
	send_tip_sensitivity = "ข้อความของคุณไม่เหมาะสม กรุณาพิมพ์ใหม่",
	send_tip_lenErr = "ข้อความแชทไม่สามารถเว้นว่างได้ และห้ามเกิน30อักษร",              --注意此处为30个字符，泰文中并不是15个字
	send_tip_fast = "คุณแชทถี่เกินไป กรุณาพักสักครู่",
	send_tip_PriLimitErr = "ส่งข้อความล้มเหลว;จำนวนชิปในตัวมีถึง1Mจะส่งข้อความได้",
	send_tip_VIPLimitErr = "ส่งข้อความล้มเหลว;VIP1ปลดล็อคการส่งข้อความ",
	label_nochat = "ช่องข้อความระบบไม่สามารถส่งข้อความได้",
	toggle_noprivate = "ปิดช่องแชทส่วนตัว",
	toggle_nohall = "ปิดช่องแชทล็อบบี้",
	horn_Tip = "โทรโข่งจะแสดงคำพูดคุณที่ระบบประกาศให้ผู้เล่นทั้งหมดเห็นข้อความนี้",
	horn_Placeholder = "กรุณากดกรอกข้อความ...",
	horn_remainder = "ปัจจุบันโทรโข่งเหลือ :",
	horn_stop = "ภายในเกมห้ามใช้โทรโข่งส่งข้อความ",
	copy_succ = "คัดลอกสำเร็จ",
	condition_chip = "ปัจจุบันชิปมีถึง1M",
	limit_tips = "ปัจจุบันยังไม่ปลดล็อคแชท",
	condition_vip = "เป็นVIP3จะปลดล็อคการแชท",
	condition_phone = "บันทึกการส่งชิป",
	condition_label = "เงื่อนไขปลดล็อคการแชท",
	delete = "ลบเพื่อน",
	BtnAddFriend = "เพิ่มเพื่อน",
	connectfriendReturn = "คำขอส่งไปแล้ว",
	systemWarnName = "System Information",
	systemWarnMsg = [[ระหว่างสนทนาหากพบมีเนื้อหาเกี่ยวข้องกับการส่งชิป ขอรหัสผ่านบัญชี 
หรือขอรหัสOTPต่างๆ ห้ามให้รหัสเหล่านี้แก่ผู้อื่นโดยเด็ดขาด 
เพื่อความปลอดภัยในทรัพย์สินท่านเอง 
โปรดตรวจสอบตัวตนอีกฝ่ายให้ดีก่อน เพื่อป้องกันมิจฉาชีพทุจริต]],
	systemWarnKeyWord = {
		"ส่งชิป",
		"ขอรหัส",
		"OTP",
		"รหัส",
		"รหัสผ่าน",
		"ขาย",
		"sms",
		"ซื้อ",
	},
	goldMedal = "เหรียญทอง",
}

return lan