local lan = {
    TimeLabel = "活动时间:",
    Time = "26/02/2021\n07/03/2021",
    OnceBtn = "抽一次",
    MoreBtn = "抽十次",
    ChipPrice = "20000",
    KeyPrice = "1",
    TimesNotEnough = "您的每日筹码抽奖次数已达上限，通过寻宝礼包可获取更多抽奖次数",
    ChipNotEnough = "当前筹码不足，无法参与抽奖",
    TicketNotEnough = "当前钥匙不足，无法参与钥匙抽奖\n请前往寻宝礼包收集",
    RewardRecord = "恭喜【%s】获得超级大奖%s",
    ----------------------------------------
    Tips_Title = "规则",
    Tips_Des = "活动期间，参与扭蛋抽奖可获得不同品级材料奖励哦。\n【普通奖励】可获得稀有材料，史诗材料。\n【特殊奖励】可获得传说材料，幸运玩家还可获得点卡实物大奖。",
    Tips_ShareDes = "大奖抽不停！快去邀请您的小伙伴一起参与吧",
    Tips_ChipLabel = "筹码抽奖",
    Tips_ChipDes1 = "每日可抽奖次数x2",
    Tips_ChipDes2 = "每日可抽奖次数x250",
    Tips_ChipDes3 = "每日可抽奖次数x500",
    Tips_ChipDes4 = "每日可抽奖次数x2000",
    Tips_ChipDes5 = "每日可抽奖次数x5000",
    Tips_ChipVip1 = "VIP 0",
    Tips_ChipVip2 = "VIP 1-2",
    Tips_ChipVip3 = "VIP 3-9",
    Tips_ChipVip4 = "VIP 10-17",
    Tips_ChipVip5 = "VIP 18+",
    Tips_KeyLabel = "钥匙抽奖",
    Tips_KeyGift = "寻宝礼包",
    Tips_KeyDes = "购买寻宝礼包可获得【钥匙】并有机会获得高级材料",
    Tips_KeyLimit = "无限制",
    Tips_GOBtn = "GO",
}

return lan