local lan =
{
	Info = "资讯",
	Gift = "赠送",
	GiftRecord = "赠送记录",
	InputID = "请输入玩家ID",
	NoSearchResult = "未搜索到指定玩家",
	SearchFllowPlayers = "搜索到以下玩家",
	RecommendPlayer = "系统推荐玩家",
	GiftRecord_Lab = "赠送记录",
	Collect = "收礼记录",
	Summary = "月汇总",

	Name = "昵称",
	ID = "ID",
	Level = "VIP等级",
	SendCost = "赠送手续费",
	Tel = "电话",
	TelEng = "Tel:",
	Add = "地址",
	AddEng = "Add:",
	ChipsNumber = "筹码数量",
	TotalcollectionText = "收礼总记录",
	TotalGiftDelivery = "赠送总记录",
	Weeklygrantlist = "周赠送榜",
	Time = "时间",
	GiveAgain = "再次赠送",
	Search = "搜索",
	Get = "领取",
	UnGet = "已领取",

	connectfriendReturn1 = "不能给自己赠送礼物",

	ownCanEdit = "您已达到VIP20，点击空白处开始上传个人资讯!",
	phoneNumberTip = "上传失败，请填写正确的手机号码",
	fbTip = "上传失败，Facebook地址格式错误",
	lineTip = "上传失败，Line地址格式错误",
	EditSure = "确认上传资讯信息",
	btnOk = "确定",
	emptyInfo = "暂无资讯内容",
	needVip = "达到VIP20的玩家可以发布个人资讯！",
	EditSelf = "您暂未发布个人资讯，点击这里开始上传！",
	MyInfo = "我的资讯",
	Upload = "上传",
	InputTel = "输入电话",
	InputAdd = "输入地址",
	InputFB = "输入Facebook联系方式",
	InputLine = "输入Line联系方式",
	InputDes = "输入我的介绍",
	UploadSucceed = "上传成功",

	NameEx = "Name",
	IDEx = "11111",
	TelEX = "09-1111-1111",
	AddEx = "Bangkok",
	guide_step1_Content = "รายละเอียดข้อมูล",
	guide_step1_1 = "可查看更多详情资讯哦~",
	guide_step1_2 = "点击红色箭头",
	guide_step1_Btn = "ถัดไป",
	guide_step2_Content = "รายละเอียดข้อมูล",
	guide_step2_1 = "想进一步了解更多资讯",
	guide_step2_2 = "可以添加他们FB、line联系他们哦~祝您游戏愉快~",
	guide_step2_Btn = "ถัดไป",
	guide_step3_Content = "รายละเอียดข้อมูล",
	guide_step3_1 = "ยินดีด้วยคุณอัพVIP3สำเร็จ",
	guide_step3_2 = "解锁赠送功能，绑定手机即可开启接收和赠送好友筹码哦，去开启你的赠送之旅吧~",
	guide_step3_Btn = "ลองไปดู",
}

return lan