local lan =
{
	Info = "ข้อมูล",
	Gift = "ส่ง",
	GiftRecord = "บันทึกการส่ง",
	InputID = "กรุณากรอกIDผู้เล่น",
	NoSearchResult = "ค้นหาไม่พบผู้เล่นดังกล่าว",
	SearchFllowPlayers = "ค้นหาเจอผู้เล่นดังกล่าว",
	RecommendPlayer = "ระบบแนะนำเพื่อน",
	GiftRecord_Lab = "บันทึกการส่ง",
	Collect = "บันทึกการรับ",
	Summary = "สรุปรายเดือน",

	Name = "ชื่อเล่น",
	ID = "ID",
	Level = "ระดับVIP",
	SendCost = "กำไรส่งชิป",
	Tel = "เบอร์ติดต่อ",
	TelEng = "Tel:",
	Add = "ที่อยู่",
	AddEng = "Add:",
	ChipsNumber = "จำนวนชิป",
	TotalcollectionText = "บันทึกการรับทั้งหมด",
	TotalGiftDelivery = "บันทึกการส่งทั้งหมด",
	Weeklygrantlist = "อันดับการส่งชิปประจำสัปดาห์",
	Time = "เวลา",
	GiveAgain = "ส่งชิปอีกครั้ง",
	Search = "ค้นหา",
	Get = "รับ",
	UnGet = "รับแล้ว",

	connectfriendReturn1 = "ไม่สามารถส่งให้ตนเองได้",

	ownCanEdit = "คุณถึงVIP20แล้ว กดคลิกที่ช่องว่างจะเริ่มอัพโหลดข้อมูลส่วนตัว",
	phoneNumberTip = "อัพโหลดล้มเหลว กรุณากรอกเบอร์โทรศัพท์ที่ถูกต้อง",
	fbTip = "อัพโหลดล้มเหลว รูปแบบของFacebookไม่ถูกต้อง",
	lineTip = "อัพโหลดล้มเหลว รูปแบบของLINEไม่ถูกต้อง",
	EditSure = "ยืนยันข้อมูลการอัปโหลด",
	btnOk = "ตกลง",
	emptyInfo = "ขณะนี้ไม่มีข้อมูลใดๆ",
	needVip = "ผู้เล่นที่ถึงVIP20จะสามารถเปิดใช้งานข้อมูลส่วนตัวได้",
	EditSelf = "ตอนนี้คุณยังไมได้ใช้งานข้อมูลส่วนตัว กดที่นี่เพื่อเริ่มอัพโหลดใช้งาน",
	MyInfo = "ข้อมูลของฉัน",
	Upload = "อัพโหลด",
	InputTel = "กรอกเบอร์ติดต่อ",
	InputAdd = "กรอกที่อยู่",
	InputFB = "กรอกที่ติดต่อFacebook",
	InputLine = "กรอกที่ติดต่อLINE",
	InputDes = "กรอกแนะนำตนเอง",
	UploadSucceed = "อัพโหลดสำเร็จ",

	NameEx = "Name",
	IDEx = "11111",
	TelEX = "09-1111-1111",
	AddEx = "Bangkok",
	guide_step1_Content = "รายละเอียดข้อมูล",
	guide_step1_1 = "สามารถตรวจเช็ครายละเอียดเพิ่มเติมได้ค่ะ~",
	guide_step1_2 = "กดคลิกที่ลูกศรสีแดง~",
	guide_step1_Btn = "ถัดไป",
	guide_step2_Content = "รายละเอียดข้อมูล",
	guide_step2_1 = "ขอให้คุณเล่นเกมมีความสุขนะคะ~",
	guide_step2_2 = "ถ้าหากอยากสอบถามข้อมูลเพิ่มเติม\nสามารถแอดFacebook หรือ LINEเพื่อติดต่อพวกเขา",
	guide_step2_Btn = "ถัดไป",
	guide_step3_Content = "รายละเอียดข้อมูล",
	guide_step3_1 = "ยินดีด้วยคุณอัพVIP3สำเร็จ",
	guide_step3_2 = "ปลดล็อคฟังก์ชั่นส่งชิป และหากผูกเบอร์โทรศัพท์จะใช้งานได้ทันที\nสามารถรับและส่งชิปให้กับเพื่อนของคุณได้\nรีบไปเปิดใช้ฟังก์ชั่นส่งชิปกันนะคะ",
	guide_step3_Btn = "ลองไปดู",
}

return lan