local lan =
{
	btnFB = "Facebook",
	btnLine = "Line",
	btnApple = "Sign in",
	btnGuest = "นักท่องเที่ยว",
	btnOppo = "ล็อกอิน OPPO",
	connectFail = "เชื่อมต่อล้มเหลว ลองใหม่อีกครั้งนะ!",
	facebookLoginFailed = "Facebookล็อคอินล้มเหลว",
	facebookLoginCheckFailed = "Facebookล็อคอินยืนยันล้มเหลว",
	guessLoginFailed = "ล็อคอินบัญชีนักท่องเที่ยวล้มเหลว",
	tokenCheckFailed = "tokenยืนยันล้มเหลว",
	loadPlayerDataFailed = "ดาวโหลดข้อมูลผู้เล่นล้มเหลว",
	regToPublisherFailed = "สมัครpublisherล้มเหลว",
	loadReConnectDataFailed = "ดาวโหลดข้อมูลผู้เล่นเชื่อมต่อใหม่ล้มเหลว",
	lineLoginFailed = "Lineล็อคอินล้มเหลว",
	lineLoginCheckFailed = "Lineล็อคอินยืนยันล้มเหลว",
	exit = "ออกจากล็อบบี้",
	noticeTitle = "ประกาศ",
	noticeContent = "ขณะนี้ไม่สามารถอ่านข้อมูลประกาศได้ชั่วคราว",
	loginTips = "รางวัลผูกบัญชีสามารถรับได้ครั้งเดียวเท่านั้น\nเพื่อรับประกันความปลอดภัยบัญชีเกมของคุณ\nแนะนำล็อกอินด้วยบัญชี FACEBOOK หรือ LINE",
	loadingTips = "LOADING...",
	LoadingWarn = "ห้ามมิให้ผู้เล่นกระทำการพนันจริงทุกรูปแบบบนแพลตฟอร์มนี้โดยเด็ดขาด",
	Phone = "โทรศัพท์",
	PhoneLogin = "ล็อคอินด้วยเบอร์",
	PhoneNum = "เบอร์โทรศัพท์",
	OTPCode = "รหัสยืนยัน OTP",
	GetCode = "ส่งขอ OTP",
	PhoneNum_Tip = "โปรดกรอกเบอร์โทรศัพท์ที่ถูกต้อง",
	ChoosePhoneNum = "โปรดเลือกบัญชี",
	UsePhoneLogin = "โปรดใช้เบอร์โทรศัพท์ล็อคอิน",
	Commit = "ยืนยัน",
	PhoneGetCodeFail = "เบอร์นี้ยังไม่ได้ผูกบัญชี",
	PhoneGetCodeSucc = "รับรหัสยืนยันสำเร็จ",
	VerCodeFail = "โปรดกรอกรหัสยืนยันที่ถูกต้อง",

	fbLoginErr = "ผู้ใช้งานบัญชี 【Facebook】 ล็อคอินไม่ได้ \nสามารถล็อคอินผ่าน【เบอร์โทรศัพท์】\nที่ผูกกับบัญชีไว้จะสามารถเข้าเกมได้",
	phoneLoginBtn = "ล็อคอินเบอร์โทรศัพท์",
	updateMsg = "เวอร์ชั่นนี้ไม่สามารถใช้Facebookล็อกอินได้ กรุณาไปที่Google Playเพื่ออัปเดตเวอร์ชั่น",
	btnGo = "ไปอัปเดต",
	btnCancel = "ยกเลิก",
}

return lan