local lan =
{
	btnFB = "Facebook",
	btnLine = "Line",
	btnApple = "Sign in",
	btnGuest = "游客登录",
	btnOppo = "OPPO登录",
	connectFail = "啊哦！连接失败了，再试一试吧！",
	facebookLoginFailed = "Facebook登录失败",
	facebookLoginCheckFailed = "Facebook登录验证失败",
	guessLoginFailed = "游客登录失败",
	tokenCheckFailed = "token验证失败",
	loadPlayerDataFailed = "加载玩家道具信息失败",
	regToPublisherFailed = "注册publisher失败",
	loadReConnectDataFailed = "加载玩家重连数据失败",
	lineLoginFailed = "Line登录失败",
	lineLoginCheckFailed = "Line登录验证失败",
	exit = "退出",
	noticeTitle = "公告",
	noticeContent = "暂时无法获取公告信息",
	loginTips = "账号连接奖励一个账号仅可领取一次\n为保证您的游戏记录安全，建议您使用\nFACEBOOK 或 LINE账号登陆",
	loadingTips = "LOADING...",
	LoadingWarn = "明令禁止玩家在游戏内进行各种性质的赌博行为",
	Phone = "电话",
	PhoneLogin = "电话登录",
	PhoneNum = "电话号码",
	OTPCode = "OTP验证码",
	GetCode = "发送OTP",
	PhoneNum_Tip = "请输入正确的手机号码",
	ChoosePhoneNum = "请选择账号",
	UsePhoneLogin = "请使用telephone登录",
	Commit = "确定",
	PhoneGetCodeFail = "该手机未绑定账号",
	PhoneGetCodeSucc = "获取验证码成功",
	VerCodeFail = "请输入正确的验证码",

	fbLoginErr = "ผู้ใช้งานบัญชี 【Facebook】 ล็อคอินไม่ได้ \nสามารถล็อคอินผ่าน【เบอร์โทรศัพท์】\nที่ผูกกับบัญชีไว้จะสามารถเข้าเกมได้",
	phoneLoginBtn = "ล็อคอินเบอร์โทรศัพท์",
	updateMsg = "当前版本无法登录facebook，请访问Google Play更新您的版本。",
	btnGo = "前往",
	btnCancel = "取消",
}

return lan