local lan = {
    card1 = "บัตรรายเดือนสุดคุ้ม",
    card2 = "บัตรรายเดือนซูพรีม",
    dis = "โปรโมชั่น",
    totalVa = "มูลค่ารวม <size=26>%s</size>",
    morePrivi = "สิทธิ์พิเศษ",
    enjoyPrivi = "สิทธิพิเศษ",
    chipRew = "รางวัลชิป%s",
    everyRew = "รางวัลล็อค%sอินประจำวัน",
    limiFrame = "กรอบโปรไฟล์%sจำกัดเวลา",
    loginDouRew = "รางวัลล็อคอิน%sเพิ่มเท่าจำกัดเวลา",
    vipDotExch = "แลกแต้มVIP%s",
    relief = "รับชิปช่วยเหลือ%s",
    sendReve = "ค่าธรรมเนียมการส่ง%s",
    reliefTime = "จำนวนชิปช่วยเหลือ%s",
    everyVipSuffer = "VIPแต้มEXPแต่ละวัน%s",
    actiCard1 = "ยินดีด้วยเปิดใช้บัตรรายเดือนสุดคุ้ม",
    actiCard2 = "ยินดีด้วยเปิดใช้บัตรรายเดือนซูพรีม",
    priviDeta = "รายละเอียดสิทธิ์พิเศษ",
    overFlow = "สุดคุ้ม",
    extreme = "ซูพรีม",
    receRew = "รับรางวัล",
    renew = "ต่ออายุ",
    tomorrowRece = "พรุ่งนี้ค่อยมารับใหม่",
    extremeCard = "บัตรรายเดือนพิเศษ",
    vipSuffer = "VIPแต้มEXP",
    overFlowAndExtreme = "คุ้มค่า+พิเศษ",
    day = "คงเหลือ <%s><size=26>%s</size></color> วัน",
    hour = "คงเหลือ <%s><size=26>%s</size></color> ชั่วโมง",
    minute = "คงเหลือ <%s><size=26>%s</size></color> นาที",
    lose = "บัตรรายเดือนจะหมดอายุ",
    tip = "สิทธิ์พิเศษบัตรรายเดือนหลังซื้อแล้วจะมีผลทันที มีผลระยะเวลา30วัน",
    expiry = "%s หมดอายุแล้ว",

    Privi1 = "กรอบโปรไฟล์พิเศษจำกัดเวลา <color=#E0A21EFF><size=22>+1</size></color>",
    Privi2 = "ชิปช่วยเหลือที่รับได้ <color=#E0A21EFF><size=22>+1</size></color>",
    Privi3 = "รางวัลล็อคอินจำกัดเวลาเพิ่มเท่า <color=#E0A21EFF><size=22>x2</size></color>",
    Privi4 = "VIPแต้มEXPแต่ละวัน <color=#E0A21EFF><size=22>+6</size></color>",

    Privi5 = "ค่าธรรมเนียมการส่ง <color=#E0A21EFF><size=22>-10%</size></color>",
    Privi6 = "ชิปช่วยเหลือที่รับได้ <color=#E0A21EFF><size=22>+1</size></color> และรางวัล <color=#E0A21EFF><size=22>+2000</size></color>",
    Privi7 = "VIPแต้มEXPแต่ละวัน <color=#E0A21EFF><size=22>+16</size></color>",

    Privi8 = "แต้มVIPแลกชิป+รางวัลชิป <color=#E0A21EFF><size=22>+10%</size></color>",
    Privi9 = "แต้มVIPแลกชิป+รางวัลชิป <color=#E0A21EFF><size=22>+20%</size></color>",
    Privi10 = "ชิปช่วยเหลือที่รับได้ <color=#E0A21EFF><size=22>+2</size></color> และรางวัล <color=#E0A21EFF><size=22>+2000</size></color>",
}

return lan