local lan = {
    card1 = "超值月卡",
    card2 = "至尊月卡",
    dis = "优惠",
    totalVa = "总价值 <size=26>%s</size>",
    morePrivi = "更多特权",
    enjoyPrivi = "尊享特权",
    chipRew = "筹码奖励%s",
    everyRew = "每日登陆奖励%s",
    limiFrame = "限时头像框%s",
    loginDouRew = "限时登陆奖励翻倍%s",
    vipDotExch = "VIP点兑换%s",
    relief = "救济金领取%s",
    sendReve = "赠送税收%s",
    reliefTime = "救济金次数%s",
    everyVipSuffer = "每日VIP经验%s",
    actiCard1 = "恭喜激活超值月卡",
    actiCard2 = "恭喜激活至尊月卡",
    priviDeta = "特权详情",
    overFlow = "超值",
    extreme = "至尊",
    receRew = "领取奖励",
    renew = "续费",
    tomorrowRece = "明日再领取",
    extremeCard = "尊享月卡",
    vipSuffer = "VIP经验",
    overFlowAndExtreme = "超值+尊享",
    day = "剩余 <%s><size=26>%s</size></color> 天",
    hour = "剩余 <%s><size=26>%s</size></color> 小时",
    minute = "剩余 <%s><size=26>%s</size></color> 分钟",
    lose = "月卡即将失效",
    tip = "月卡特权自购买后生效享有，有效期为30天",
    expiry = "%s 已失效",

    Privi1 = "尊享专属限时头像框 <color=#E0A21EFF><size=22>+1</size></color>",
    Privi2 = "救济金领取次数 <color=#E0A21EFF><size=22>+1</size></color>",
    Privi3 = "限时登陆奖励翻倍 <color=#E0A21EFF><size=22>x2</size></color>",
    Privi4 = "每日VIP经验 <color=#E0A21EFF><size=22>+6</size></color>",

    Privi5 = "赠送税收 <color=#E0A21EFF><size=22>-10%</size></color>",
    Privi6 = "救济金领取次数 <color=#E0A21EFF><size=22>+1</size></color>，且奖励 <color=#E0A21EFF><size=22>+2000</size></color>",
    Privi7 = "每日VIP经验 <color=#E0A21EFF><size=22>+16</size></color>",

    Privi8 = "VIP点兑换筹码 <color=#E0A21EFF><size=22>+10%</size></color> 筹码奖励",
    Privi9 = "VIP点兑换筹码 <color=#E0A21EFF><size=22>+20%</size></color> 筹码奖励",
    Privi10 = "救济金领取次数 <color=#E0A21EFF><size=22>+2</size></color>，且奖励 <color=#E0A21EFF><size=22>+2000</size></color>",
}

return lan