local lan = {
    nowLiveness = "当前活跃度:%s",
    goBtn = "前往",
    getBtn = "领取",
    convertBtn = "兑换",
    reward = "奖励:",
    livenessBox = "%s活跃度宝箱：有机率获得",
    realBox = "实物宝箱：完成所有任务有机率获得",
    taskName1 = "新手每日签到1天",
    taskName2 = "第二天登录",
    taskName2_3 = "第三天登录",
    taskName2_7 = "第七天登录",
    taskName3 = "游戏在线1小时",
    taskName4 = "每日分享1位好友",
    taskName5 = "参与每日转盘1次",
    taskName6 = "参与%s场游戏比赛",
    taskName7 = "购买首冲礼包",
    taskName13 = "绑定FB或其他第三方",
    taskName14 = "添加任意游戏好友",
    taskName16 = "任意加入2个游戏",
    taskName17 = "完善游戏信息",
    taskName20 = "每日赢分30K",
    taskReward1 = "完成新手签到大奖",
    taskReward2 = "完成次日登录大奖",
    taskReward3 = "完成累计在线大奖",
    taskReward4 = "完成分享好友大奖",
    taskReward5 = "完成每日转盘大奖",
    taskReward6 = "完成游戏比赛大奖",
    taskReward7 = "完成购买礼包大奖",
    taskReward14 = "完成添加好友大奖",
    taskReward20 = "完成每日赢分大奖",
    share_content = "玩转ROYAL CASINO 快来和我一起参与新手任务，收集点卡碎片吧~里面有丰富大奖，还有超多福利等着你哦~",
    finishText1 = "任务以结束",
    finishText2 = "将自动为您开启碎片任务",
    debris = "当前碎片不足",
    ruleTitle = "อธิบาย",
    ruleText = "任务描述：当你完成你的创业工作，你可以得到一个记分卡碎片礼物，收集多达70记分卡碎片。你可以去实体店兑换2万积分的卡奖。点卡碎片也可以用来参与狩猎活动。收集一定数量的碎片，开启额外的主动寻宝。除了筹码和记分碎片，还有机会直接拿到一张记分卡。",
    bottomText = "ช่องทางที่ได้รับ:"
    .."\nเซ็นชื่อมือใหม่ ภารกิจมือใหม่"
    .."\nเข้าร่วมแข่งขัน ซื้อแพ็คเกจ",
}

return lan