local lan = {
    send = "赠送",
    propSend = "道具赠送",
    sendNum = "赠送数量",
    receiverId = "接收人ID",
    receiverNick = "接收人昵称",
    haveNum = "拥有%s个",
    notnot = "暂无",
    affirmSend = "确定赠送",
    sendError1 = "请输入正确的数量",
    sendError2 = "请输入正确的接收人ID。",
    sendError3 = "不要顽皮，你知道这样的操作是毫无意义的",
    sendError4 = "不得超过自身拥有数。",
    affirmTip = "是否确认赠送给ID：<color=#FFBA36FF>%s</color> 玩家 <color=#FFBA36FF>%s</color> 道具 <color=#FFBA36FF>%s</color> 个。为了您的财产安全，请认真核查信息！",
    time = "时间",
    prop = "道具",
    num = "数量",
    notRecord = "暂无赠送记录。",
    receiveProp = "用户 <color=#FFBA36FF>%s</color> 赠送给您 <color=#FFBA36FF>%s</color> 个 <color=#FFBA36FF>%s</color> 道具，请查收！",
    sendRecord = "赠送记录",
    sendSuccess = "赠送成功",
}
return lan