local lan =
{
	btn_BatteryGift = "แพ็คเกจปืนใหญ่\nพิเศษลิมิเต็ด",
	btn_SuperDailyGift = "แพ็คเกจรายวัน\nสุดคุ้ม",
	AirDeals = "ยิงเครื่องบิน",
	NoviceBtn = "ของขวัญมือใหม่",
	FundBtn = "กองทุน7วัน",
	btn_EveryGift = "แพ็คยิงปลา",
	AchievementGiftBtn = "แพ็คจำกัดเวลา",
	LuckyBtn = "วงล้อนำโชค",
	TreasureBtn = "ล่าสมบัติประจำวัน",
	tips_fishGift = "วันนี้คุณได้ซื้อไปแล้ว พรุ่งนี้ค่อยมาซื้อใหม่นะ",
	slot_icon = "แพ็คเกจ",
	VipThreeCard = "การ์ดอัพระดับ VIP3",
	BrokeBtn = "พลิกชะตาโชคดี",
	PayBtn = "เติมเงินมีรางวัล",
	FortuneCatBtn = "กาชาปองแมวกวัก",
	BrokeBigBtn = "แพ็คเกจพลิกชะตา",
	ElkLimitGiftBtn = "Flash Sale\nคริสต์มาส",
	DragonBtn = "วงล้อเทพเจ้ามังกร",
	AirplaneBtn = "วงล้อนำโชค",
	BatteryLotteryBtn = "จับรางวัล\nปืนใหญ่ดนตรี",
	MonthCardBtn = "ซื้อบัตรรายเดือน",
	SpecialOfferGiftBtn = "แพ็คสงกรานต์",
	CommonHolidayGiftBtn = "แพ็คพิเศษ",
	["VipThreeCardView"] = {
		tip1title = "ส่งชิป",
		tip1text = "เปิดใช้งานฟังก์ชั่นส่งชิป\n1.สามารถส่งชิปให้กับเพื่อนได้\n2.ทุกครั้งการส่งชิปจะต้องส่งไม่ต่ำกว่า900,000ชิป",
		tip2title = "ปลดล็อคแชทส่วนตัว",
		tip2text = "1.ปลดล็อคสิทธิ์การใช้ช่องแชท\n2.ปลดล็อคสิทธิ์การใช้แชทส่วนตัว",
		tip3title = "ปลดล็อคห้องระดับกลางทุกเกม",
		tip3text = "",
	},
	Birthday = "โปรโมชั่นวันเกิด",
}

return lan