local lan = 
{	
	["primary"] = "初级场",
	["middle"] = "中级场",
	["advanced"] = "高级场",
	["expert"] = "专家场",
	VIPSpot = "VIP点",
	Exchange = "兑换中心",
	VIP_Level = "VIP %s",
	label_Recharge = "再充值 %s",
	btn_Recharge = "去充值",
	nextVIP_Level = "下级VIP",
	accumulatedValue = "累计充值",
	accumulatedChips = "累计消耗筹码",
	horn = "升级道具奖励",
	sendLimit = "赠送筹码上限",
	loginAward = "最低赠送额",
	subsidy = "额外救济金",
	gameUnlock = "游戏场解锁",
	btn_More = "更多权益",
	sendTax = "赠送税收减少",
	sendSurplus = "赠送剩余锁定",
	sendTimeLock = "赠送时间锁定",
	buyCD = "商品购买CD",
	VIPSpotRatio = "VIP点兑换比",
	VIPSpotRatio_exchange = "当前等级，可享受<color=#FFF900FF>%s</color>倍兑换比例",
	VipLottery = "彩票奖金额外加成",
	btn_Exchange = "兑换",
	label_VIPfull = "您的VIP等级已到达顶级",
	tip_vipSpotMax = "已达单次兑换上限",
	maxGiveCount = "无限制",
	chip = "筹码",
	day = "/天",
	power = "倍",
}

return lan