local lan = 
{	
	["primary"] = "ห้องมือใหม่ ",
	["middle"] = "ห้องระดับกลาง ",
	["advanced"] = "ห้องระดับสูง ",
	["expert"] = "ห้องมืออาชีพ ",
	VIPSpot = "แต้มVIP",
	Exchange = "ศูนย์แลกเปลี่ยน",
	VIP_Level = "VIP %s",
	label_Recharge = "เติมเงินอีก %s฿",
	btn_Recharge = "ไปเติมเงิน",
	nextVIP_Level = "VIPถัดไป",
	accumulatedValue = "สะสมเติมเงิน",
	accumulatedChips = "สะสมจำนวนการใช้ชิป",
	horn = "รางวัลการอัพเกรด",
	sendLimit = "จำนวนชิปที่ส่งได้",
	loginAward = "ส่งชิปต่ำสุด",
	subsidy = "ชิปช่วยเหลือพิเศษ",
	gameUnlock = "ปลดล็อคระดับห้อง",
	btn_More = "ตรวจสอบสิทธิพิเศษ",
	sendTax = "ลดค่าธรรมเนียมการส่ง",
	sendSurplus = "ล็อคชิปคงเหลือในตัว",
	sendTimeLock = "ล็อคเวลาการส่ง",
	buyCD = "CD สั่งซื้อรายการ",
	VIPSpotRatio = "ปัจจุบันระดับ สามารถได้%sเท่าอัตราแลกเปลี่ยน",
	VIPSpotRatio_exchange = "ปัจจุบันระดับ สามารถได้<color=#FFF900FF>%s</color>เท่าอัตราแลกเปลี่ยน",
	VipLottery = "รางวัลโบนัสล็อตเตอรี่เพิ่มขึ้น",
	btn_Exchange = "แลกเปลี่ยน",
	label_VIPfull = "VIPของคุณถึงระดับสูงสุดแล้ว",
	tip_vipSpotMax = "แลกภายในครั้งเดียวถึงจำนวนจำกัด",
	maxGiveCount = "ไม่จำกัด",
	chip = "ชิป",
	day = "/วัน",
	power = "เท่า",
}

return lan