---------------------------------
-- region ResourceDefine.lua    -
-- Date: 2019.9.17       -
-- Desc: 动态加载资源对应的ab文件(文件名不能重复)
-- Author: Bin        -
---------------------------------

local ResourceDefine = {}

ResourceDefine.Image = {}
ResourceDefine.Sound = {}
ResourceDefine.Prefab = {}
--登录界面预加载配置
ResourceDefine.PreloadAssets = {
	Prefab = {
		"HallView",
		"FreeChipsCollectionView",
		"StoreView",
		"MiniCard",
		"yxrk_2001",
		"yxrk_2002",
		"yxrk_2003",
		"yxrk_2004",
		"yxrk_2005",
		"yxrk_3001",
		"yxrk_3002",
		"yxrk_3003",
		"yxrk_3004",
		"yxrk_3005",
		"yxrk_3007",
		"LuckyTurntableView",
		"ChipCounter",
		"DiamondCounter",
		"IntegralCounter",
		"VipCounter",
		"FreeChipsIcon",
		"SelectGiftIcon",
		-- "AnniversaryTurntableView"
	},
	Sound = {
		 "BGM_Hall",
		--"BGM_FreeChipsCollection",
	}
}


local ImageDefine = {

	MonthActivity = {
		"fx_17",
		"share_1_1",
		"share_1_2",
	},
	temp_V3 = {
		"prop_img_1135",
		"prop_img_1136",
		"prop_img_20081",
		"prop_img_20082",
		"img_yxrk_3004",
		--"img_select_1015"
	},
	temp_V4 = {
		"prop_img_67",
		"prop_img_1137",
		"prop_img_1138",
		"prop_img_3049",
		"prop_img_3050",
		"loading_psj",
		"share_1_7",
		"prop_img_20065",
		"prop_img_20083",
		"prop_img_20084",
		"img_select_1014",
		"img_yxrk_1014",
	},
	temp_V7 = {
		"img_select_1015",
	},
	temp_V12 = {
		--"channel_ais",
		--"channel_psms",
		"prop_img_10021",
		"prop_img_10022",
		"prop_img_10023",
		"prop_img_10024",
	},
	temp_V15 = {
		"head_p_101",
		"head_p_102",
		"head_p_103",
		"head_p_104",
		"head_p_105",
		"head_p_106",
		"hxrw_fj_1_01",
		"hxrw_fj_1_02",
		"hxrw_fj_1_03",
		"hxrw_fj_1_04",
		"hxrw_fj_1_05",
		"hxrw_fj_1_06",
		"hxrw_fj_1_07",
		"hxrw_fj_1_08",
		"hxrw_fj_1_09",
		"hxrw_fj_1_10",
		"hxrw_fj_tj_1_01",
		"hxrw_fj_tj_1_02",
		"hxrw_fj_tj_1_03",
		"hxrw_fj_tj_1_04",
		"hxrw_fj_tj_1_05",
		"hxrw_fj_tj_1_06",
		"hxrw_fj_tj_1_07",
		"hxrw_fj_tj_1_08",
		"hxrw_fj_tj_1_09",
		"hxrw_fj_tj_1_10",
		"hxrw_phb_mc01",
		"hxrw_phb_mc02",
		"hxrw_phb_mc03",
		"hxrw_rw_rw_sp",
		"prop_img_3051",
		"prop_img_3052",
		"prop_img_3053",
		"loading_MarsTask",
		--"share_1_8",
		"truecard5090",
		"award_4",
	},
	temp_V18 = {
		"smrz_icon04",
		"smrz_icon05",
		"prop_img_71",
	},
	temp_V19 = {
		"img_yxrk_1017",
	},
	temp_V21 = {
		"prop_img_72",
		"prop_img_73",
		"prop_img_9058",
		"prop_img_9062",
		"prop_img_9066",
		"prop_img_9070",
		"prop_img_9074",
		"prop_img_20085",
		"prop_img_20086",
		"priceIcon_hb",
		"hxrw_fj_2_01",
		"hxrw_fj_2_02",
		"hxrw_fj_2_03",
		"hxrw_fj_2_04",
		"hxrw_fj_2_05",
		"hxrw_fj_2_06",
		"hxrw_fj_2_07",
		"hxrw_fj_2_08",
		"hxrw_fj_2_09",
		"hxrw_fj_2_10",
		"hxrw_fj_tj_2_01",
		"hxrw_fj_tj_2_02",
		"hxrw_fj_tj_2_03",
		"hxrw_fj_tj_2_04",
		"hxrw_fj_tj_2_05",
		"hxrw_fj_tj_2_06",
		"hxrw_fj_tj_2_07",
		"hxrw_fj_tj_2_08",
		"hxrw_fj_tj_2_09",
		"hxrw_fj_tj_2_10",
		"icon_dhk50",
	},
	temp_V23 = {
		"lkb_bx_01",
		"lkb_bx_02",
		"lkb_bx_03",
		"lkb_bx_04",
		"lkb_bx_05",
		"prop_img_20078",
		"prop_img_20087",
		"prop_img_20088",
		"prop_img_20089",
		"prop_img_20090",
		"prop_img_20091",
	},
	temp_V27 = {
		"hxrw_fj_3_01",
		"hxrw_fj_3_02",
		"hxrw_fj_3_03",
		"hxrw_fj_3_04",
		"hxrw_fj_3_05",
		"hxrw_fj_3_06",
		"hxrw_fj_3_07",
		"hxrw_fj_3_08",
		"hxrw_fj_3_09",
		"hxrw_fj_3_10",
		"hxrw_fj_tj_3_01",
		"hxrw_fj_tj_3_02",
		"hxrw_fj_tj_3_03",
		"hxrw_fj_tj_3_04",
		"hxrw_fj_tj_3_05",
		"hxrw_fj_tj_3_06",
		"hxrw_fj_tj_3_07",
		"hxrw_fj_tj_3_08",
		"hxrw_fj_tj_3_09",
		"hxrw_fj_tj_3_10",
		"hxrw_gj_pd",
	},
	temp_Anniversary = {
		"prop_img_80",
		"prop_img_81",
		"prop_img_20094",
		"prop_img_20095",
		"prop_img_20096",
		"prop_img_20097",
		"prop_img_20098",
		"prop_img_20099",
		"prop_img_20100",
		-- "prop_img_20101",
		-- "prop_img_20102",
		"prop_img_20103",
		"prop_img_20104",
		"prop_img_20105",
		"prop_img_20106",
		"prop_img_20108",
		"hbsc_icon1",
		"hbsc_icon2",
		"prop_img_3054",
		"prop_img_3055",
		"prop_img_3056",
		"prop_img_3057",
		"loading_anniversary",
		"img_select_1017"
	},
	temp_AgentView = {
		"prop_img_1150",
		-- "prop_img_1151",
	},
	temp_V32 = {
		"prop_img_20101",
		"prop_img_20102",
		"prop_img_20109",
		"prop_img_20110",
		"share_1_9",
	},
	temp_V36 = {
		"prop_img_82",
		"img_yxrk_1018",
		"img_select_1018",
		"img_yxrk_1019",
		"img_select_1019"
	},
	temp_V39 = {
		"prop_img_1151",
	},
	temp_V45 = {
		"prop_img_9082",
		"prop_img_9083",
		"prop_img_9084",
		"prop_img_20111",
		"prop_img_20112",
		"prop_img_20113",
		"hdrk_icon_wsj",
		"share_1_6_20221025",
	},
	temp_worldcup = {
		"circle_0",
		"circle_1",
		"circle_2",
		"circle_3",
		"circle_4",
		"circle_5",
		"circle_6",
		"circle_7",
		"circle_8",
		"circle_9",
		"circle_10",
		"circle_11",
		"circle_12",
		"circle_13",
		"circle_14",
		"circle_15",
		"circle_16",
		"circle_17",
		"circle_18",
		"circle_19",
		"circle_20",
		"circle_21",
		"circle_22",
		"circle_23",
		"circle_24",
		"circle_25",
		"circle_26",
		"circle_27",
		"circle_28",
		"circle_29",
		"circle_30",
		"circle_31",
		"circle_32",
		"square_0",
		"square_1",
		"square_2",
		"square_3",
		"square_4",
		"square_5",
		"square_6",
		"square_7",
		"square_8",
		"square_9",
		"square_10",
		"square_11",
		"square_12",
		"square_13",
		"square_14",
		"square_15",
		"square_16",
		"square_17",
		"square_18",
		"square_19",
		"square_20",
		"square_21",
		"square_22",
		"square_23",
		"square_24",
		"square_25",
		"square_26",
		"square_27",
		"square_28",
		"square_29",
		"square_30",
		"square_31",
		"square_32",
		"square_888",
		"WorldCup_Gift_1",
		"WorldCup_Gift_2",
		"WorldCup_Gift_3",
		"WorldCup_Gift_4",
		"prop_img_9085",
		"prop_img_9086",
		"prop_img_9087",
		"prop_img_9088",
		"prop_img_9089",
		"loading_worldcup",
	},
	temp_V50 = {
		"img_yxrk_1020",
		-- "img_yxrk_3013",
		"img_select_1020",
	},
	temp_V55  = {
		"prop_img_9094",
		"prop_img_9095",
		"prop_img_9096",
		"prop_img_9097",
		"img_yxrk_1026",
		"img_select_1026",
		"loading_worldcup_2",
		-- "prop_img_20087",
	},
	temp_V56 = {
		"sjb_rw_rk_icon",
	},
	temp_V57 = {
		"img_yxrk_1024",
		"img_yxrk_1028",
		--"img_select_1028",
		"prop_img_1152",
		"prop_img_9098",
		"share_1_8",
		"head_p_107",
		"head_p_108",
		"head_p_109",
	},
	temp_V59 = {
		"img_select_1028",	
	},
	temp_V60 = {
		"img_select_1024",
		"hall_bg_newyear",
		"prop_img_4011",
		"prop_img_4024",
		"prop_img_4018",
		"prop_img_4019",
		"store_ytpt",
		"store_dgpt",
		"store_sdjpt",
		"prop_img_20114",
		"prop_img_20115",
		"prop_img_20116",
		"prop_img_20117",
		"ljzf_sdj_lb01",
		"ljzf_sdj_lb02",
	},
	temp_V61 = {
		"prop_img_4020",
		"prop_img_4021",
		"prop_img_4023",
		"prop_img_4022",
		"prop_img_4025",
		"loading_sd",
		"loading_yd",
	},
	temp_V65 = {
		"img_yxrk_1025",
		"img_select_1025",
		"prop_img_83",
	},
	temp_V70 = {
		"head_p_110",
		"head_p_111",
		"head_p_112",
		"prop_img_9099",
		"prop_img_9100",
		"prop_img_9108",
	},
	temp_V72 = {
		"channel_bay",
		"channel_kbank",
		"channel_ktb",
		"img_yxrk_1021",
		"img_select_1021",
	},
	temp_V79 = {
		"prop_img_9122",
		"prop_img_9123",
		"prop_img_9124",
		"prop_img_9125",
		"prop_img_9126",
		"prop_img_9127",
		-- "prop_img_9128",
		"prop_img_20118",
		"prop_img_20119",
		"channel_ais",
		"channel_dcb",
		"channel_psms",
		"img_yxrk_1027",
		"img_select_1027",
	},
	temp_water = {
		"prop_img_97",
		"prop_img_1153",
		"prop_img_1154",
		"prop_img_98",
		"prop_img_99",
		"prop_img_100",
		"prop_img_101",
		"prop_img_102",
		"prop_img_103",
		"prop_img_3058",
		"prop_img_3059",
		"prop_img_3060",
		"prop_img_3061",
		"prop_img_20125",
		"prop_img_20126",
		"cgxb_icon_30370",
		"cgxb_icon_30371",
		"cgxb_icon_30372",
		"cgxb_icon_30373",
		"cgxb_icon_30374",
		"cgxb_gl_dx01",
		"cgxb_gl_dx02",
		"cgxb_gl_dx03",
		"cgxb_gl_dx04",
		"cgxb_gl_dx05",
		"cgxb_gl_dx06",
		"cgxb_gl_dx07",
		"cgxb_gl_dx08",
		"cgxb_gl_dx09",
		"cgxb_gl_dx10",
		"cgxb_gl_dxdk01",
		"cgxb_gl_dxdk02",
		"psj_phb_sw_lv",
		"psj_qd_wp_sd01",
		"psj_qd_wp_sd02",
		"psj_qd_wp_sd03",
		"psj_qd_wp_sd04",
		"loading_psj2023",
		"prop_img_9128",
		"img_yxrk_1033",
		"img_select_1033",
	},
	temp_V89 = {
		"img_yxrk_3013",
		"prop_img_9109",
		"prop_img_9110",
		"prop_img_9111",
		"prop_img_9112",
	},
	temp_V90 = {
		"img_select_1030",
		"img_yxrk_1030",
	}
}

local SoundDefine = {

	temp_V3 = {
		"CompoundBattery",
		"JadeHare_battery",
		"LotteryResult",
		"LotterySelect",
		"ShowReward"
	},
	temp_v15 = {
		"MarsBg",
		"MarsBoxOpen",
		"MarsCloseView",
		"MarsFly",
		"MarsHit",
		"MarsOpenView",
		"MarsStory1_1",
		"MarsStory1_2",
		"MarsSwitch",
	},
	temp_V18 = {
		"1lianchou",
		"10lianchou",
		"BGM_JuneMonthly",
	},
	temp_V23 = {
		"BGM_ActivityMonthly",
	},
	temp_Anniversary = {
		"celebrationBg",
		"turntableBg",
	},
	temp_V32 = {
		"10Reward",
		"anniversaryTurntable",
		"dragon",
		"turntableEnd",
		"lightning",
	},
	temp_V33 = {
		"HallBgm",
	},
	temp_worldcup = {
		"HallWorldCupBgm",
		"WorldCupClick",
	},
	temp_V60 = {
		"ChristmasBg",
	},
	temp_V65 = {
		"ChunjieBg",
	},
	temp_water = {
		"BGM_Hall_Water",
		"luckyTime_100",
		"luckyTime_101",
		"luckyTime_102",
		"luckyTime_103",
		"mapUpGrade",
		"mysticalJump",
		"mysticalPlate",
		"playDice",
		"playerBorn",
		"playerBorn_reward",
		"playerJump",
		"progress_1",
		"progress_2",
		"progress_3",
	},
}

local PrefabDefine = {
	DailyGift = {
		-- "DailyGiftAirplane",
		"DailyGiftBull",
		-- "DailyGiftBuyu",
		-- "DailyGiftDiglett",
		-- "DailyGiftDummy",
		-- "DailyGiftFourBuyu",
		"DailyGiftIcon",
		"DailyGiftPharaoh",
		-- "DailyGiftPokdeng",
		-- "DailyGiftZombie"
	},
	MonthActivity = {
		"ActiveEntryView"
	},
	temp_V3 = {
		--"NewPayGiftView",
		--"HolidayDiscountsView",
		--"TotalWaterRankView",
		-- "BatteryLotteryView",
		"GobackRewardView",
		-- "GiveGiftSearchView",
		--"BirthdayAwardView",
		-- "CompoundPanel",
		-- "GuideView",
		--"HalloweenLoginGiftView",
		-- "StoreView",
		--"HallView"
	},
	temp_V4 = {
		--"HolidayTaskView",
		--"HolidayTaskExplainView",
		--"UnlockGiftView",
		"SpecialOfferGiftView",
		-- "WaterSprinklingView",
		-- "HallView",
		-- "ActSignInView",
		"GiftExchangeView",
		-- "MonthRankView",
		-- "BatteryLotteryView",
		-- "CompoundPanel",
		"HeadFrame3049",
		"HeadFrame3050",
		"SignInProp3049",
		"SignInProp3050",
		-- "PersonalHeadChooseView",
		"SpecialRewardsView",
		"Act_NewCDKey",
		-- "MiniCard",
		-- "yxrk_1009",
		-- "yxrk_2001",
		-- "yxrk_2002",
		-- "yxrk_2003",
		-- "yxrk_2004",
		-- "yxrk_2005",
		-- "yxrk_3001",
		-- "yxrk_3002",
		"yxrk_3003",
		-- "yxrk_3004",
		-- "yxrk_3005",
		-- "yxrk_3007",
		-- "GiveGiftSearchView",
		"InfoItem",
		"FreeChipsCollectionView",
		-- "SelectGiftCollectionView",
		-- "ActivityCollectionView",
	},
	temp_V6 = {
		-- "AgentShareView",
		--"GuideView",
		"ChatPanel",
		"SelfPre",
		"ChipCounter",
		"DiamondCounter",
		"VIPCounter",
		"IntegralCounter",
		"GiveGiftSearchView",
	},
	temp_V7 = {
		-- "DailyDealsView",
		"ThirdGameTipView",
		"WarningTipView",
		"NoviceSignInView",
		--"TreasureView",
		"Act_Clause",
		--"NewPayGiftView",
	},
	temp_V12 = {
		--"HalloweenLoginGiftView",
		--"HolidayDiscountsView",
		"AgentRank",
		"AgentRevenueView",
		"AgentTaskView",
	},
	temp_V15 = {
		--"MarsTaskView",
		"MarsTaskTarget1",
		--"MarsTaskStoryView",
		--"MarsTaskRank",
		--"MarsTaskUnlockView",
		"MarsTaskAtlasView",
		--"MarsTaskIcon",
		"MarsTaskRewardsView",
		-- "HallView",
		"HeadFrame3051",
		"HeadFrame3052",
		"HeadFrame3053",
		-- "Act_FBChatGroup",
		-- "Act_NewFraudNotice",
	},
	temp_V16 = {
		"MarsTaskRank",
		--"MarsTaskView",
		--"MarsTaskEntryView",
	},
	temp_V18 = {
		"VIPBestGfitView",
		--"PersonalHeadChooseView",
		--"IdentityVerificationView",
		--"CapsuleView",
		-- "CommonHolidayGiftView",
		-- "HalloweenLoginGiftView",
		-- "HolidayDiscountsView",
		--"NewPayGiftView",
		-- "TotalWaterRankView",
	},
	temp_V21 = {
		-- "LoginView",
		-- "MarsTaskView",
		"MarsTaskTarget2",
		-- "MarsTaskStoryView",
		--"MarsTaskEntryView",
		-- "MarsTaskUnlockView",
		"TreasureNotEnoughTips",
		"GiftTurntableView",
		"AgentExView",
	},
	temp_V23 = {
		"DailyLotteryView",
		--"AutoScroll",
		--"CapsuleView",
		--"NewPayGiftView",
		-- "CommonHolidayGiftView",
	},
	temp_V27 = {
		--"MarsTaskStoryView",
		"MarsTaskTarget3",
		--"MarsTaskView",
		"MarsTaskUnlockView",
	},
	temp_V28 = {
		-- "BatteryLotteryView",
		-- "CompoundPanel",
		"CashCowIcon",
		-- "SelectGiftCollectionView",
	},
	temp_AgentView = {
		-- "AgentInvitationView",
		-- "BatteryLotteryView",
		-- "CompoundPanel",
		"AgentShareView",
	},
	temp_Anniversary = {
		-- "HallView",
		"HeadFrame3057",
		-- "CelebrationView",
		"CelebrationTipView",
		-- "AnniversaryRankView",
		"AnniversaryRewardsView",
		--"AnniversaryTurntableView",
		"GoldOwnerView",
		"InviteLotteryView",
		-- "HolidayDiscountsView",
		-- "WaterRankView",
		-- "BatteryRankView",
		-- "BatteryBookView",
		"BatteryPossessView",
		-- "BatteryEntryeffect",
		"RankCollectionView",
		--"TreasureView",
		"DailyDealsView",
		"VipRightsGiftView",
		"Battery_1011",
		-- "Battery_1123",
		"Battery_1127",
		-- "Battery_1138",
		"Battery_1139",
		"Battery_1140",
		"Battery_1141",
		"Battery_1142",
		"Battery_1143",
		"Battery_1144",
		"Battery_1145",
		"Battery_1146",
		-- "Battery_1110",
		"Battery_1125",
		-- "Battery_1129",
		-- "Battery_1136",
		"Battery_1147",
		"Battery_1148",
		"Battery_1149",
		"Battery_1151",
		-- "yxrk_3007",
		-- "CapsuleView",
		--"NewPayGiftView",
		-- "AutoScroll",
		--"StoreView",
		--"WaterRankHelpView",
		-- "LoginView",
		"MonthRankView",
		"NewbieTaskView",
		-- "CommonHolidayGiftView",
		"HeadFrame3009",
		"HeadFrame3010",
		"DailyGiftAirplane",
		"DailyGiftBuyu",
		"DailyGiftDiglett",
		"DailyGiftDummy",
		-- "DailyGiftFourBuyu",
		"DailyGiftPokdeng",
		"DailyGiftZombie",
		"TrailIOSSetUpSoundView",
		"ChipNotEnoughTips",
	},
	temp_V32 = {
		-- "AnniversaryTurntableView",
		"EntryEffect3054",
		"EntryEffect3055",
		"EntryEffect3056",
		"CelebrationView",
		"AgentInvitationView",
		-- "AnniversaryRankView",
	},
	temp_V33 = {
		"DebugView",
		"AnniversaryRankView",
		--"AnniversaryTurntableView",
	},
	temp_V36 = {
		"TreasureView",
		-- "NewPayGiftView",
		"NewPayGiftPreviewView",
		-- "BatteryLotteryView",
		"RealStoreExplainView",
		"AnniversaryTurntableView",
	},
	temp_V39 = {
		-- "BatteryBookView",
	},
	temp_V42 = {
		"BirthdayAwardView",
	},
	temp_V45 = {
		-- "HalloweenLoginGiftView",
		--"CapsuleView",
		"HeadFrame9084",
		--"HolidayDiscountsView",
		-- "NewPayGiftView",
		-- "TotalWaterRankView",
		-- "DailyLotteryView",
		"HalloweenView",
		-- "WaterRankView",
		-- "Act_Service",
	},
	temp_V46 = {
		--"IdentityVerificationView",
		-- "HolidayDiscountsView",
	},
	temp_worldcup = {
		-- "WorldCupView",
		"WorldCupMainView",
		"ScheduleBoard",
		"WorldCupRankView",
		"WorldCupGiftView",
		-- "AutoScroll",
		"WorldCupRankItem",
		"WorldCupADPageView",
		-- "HallView",
		"WorldCupMascot",
		"WorldCupBetView",
		"WorldCupMatchView",
		"WorldCupGuessView",
		"WorldCupTipsView",
		"WorldCupRecordView",
		"HeadFrame9088",
		"LoginView",
		"WorldCupRuleView",
	},
	temp_V52 = {
		"IdentityVerificationView",
	},
	temp_V55 = {
		-- "BatteryLotteryView",
		-- "SelectGiftCollectionView",
		"VerSafePassWordView",
		-- "CompoundPanel",
		-- "HallView",
		-- "WorldCupView",
	},
	temp_V56  ={
		"FlowWaterTaskView",
		"WorldCupView",
		-- "AutoScroll",
	},
	temp_V57 = {
		-- "WebServiceView",
		-- "SuperDailyGiftView",
		"Act_Service",
		"Act_FBChatGroup",
		-- "Act_NewFraudNotice",
		"CommonHolidayGiftView",
		-- "HallView",
	},
	temp_V59 = {
		"WebServiceView",
	},
	temp_V60 = {
		-- "HalloweenLoginGiftView",
		-- "HolidayDiscountsView",
		--"ActSignInView",
		"SignInProp4018",
		"SignInProp4019",
		"HeadFrame4018",
		"HeadFrame4019",
		-- "HallView",
		"UnlockGiftView",
		"HolidayTaskView",
		"HolidayTaskExplainView",
		-- "NewPayGiftView",
		--"ElkLimitGiftView",
		"WaterSprinklingView",
		"Battery_4023",
		"Battery_9094",
		-- "StoreView",
		-- "CapsuleView",
	},
	temp_V61 = {
		"ElkLimitGiftView",
		--"BatteryLotteryView",
		--"CompoundPanel",
		"BatteryExchangeShop",
		"EntryEffect4020",
		"EntryEffect4021",
		"EntryEffect4022",
		--"BatteryRankView",
		--"BatteryEntryeffect",
		"ReBirthdayView",
		"PersonalInfoView",
		"BatteryBookView",
		"StoreView",
		-- "HallView",
		-- "VerifiedView",
	},
	temp_V64 = {
		"VerifiedView",
	},
	temp_V65 = {
		"BlessLotteryView",
		"BlessSearchView",
		"DailyGiftFourBuyu",
		-- "HallView",
		--"WaterRankView",
		-- "ActivityCollectionView",
		-- "HolidayDiscountsView",
		"HalloweenLoginGiftView",
		-- "NewPayGiftView",
		-- "CapsuleView",
		-- "AutoScroll",
		"CommonWebView",
		"TotalWaterRankView",
		"Act_NewFraudNotice",
	},
	temp_V70 = {
		-- "HallView",
		"MarsTaskEntryView",
		"HeadIcon110",
		"HeadIcon111",
		"HeadIcon112",
		-- "HeadFrame9099",
		-- "HeadFrame9100",
		-- "MarsTaskView",
		"MarsTaskIcon",
	},
	temp_V73 = {
		"CommonExplainView",
		"NewPayGiftView",
		--"SelectGiftCollectionView",
		"HolidayDiscountsView",
		"CapsuleView",
		"AutoScroll",
		"MiniCard",
		"yxrk_1009",
		"yxrk_2001",
		"yxrk_2002",
		"yxrk_2003",
		"yxrk_2004",
		"yxrk_2005",
		"yxrk_3001",
		"yxrk_3002",
		"yxrk_3004",
		"yxrk_3005",
		"yxrk_3007",
	},
	temp_V75 = {
		-- "SuperDailyGiftView",
		"HeadFrame9099",
		-- "HeadFrame9100",
	},
	temp_V79 = {
		"TreasureExchangeTips",
		-- "GuideView",
	},
	temp_water = {
		"ActSignInView",
		"Battery_1154",
		"BatteryLotteryView",
		"DailyTurntableView",
		"MonopolyView",
		"MonopolyRuleView",
		"WaterIcon",
		-- "HallView",
		"CompoundPanel",
		"SelectGiftCollectionView",
		-- "OnlineAward",
		"SuperDailyGiftView",
		"MonopolyGiftView",
		"EntryEffect3059",
		"EntryEffect3060",
		"EntryEffect3061",
		"BatteryEntryeffect",
		"BatteryRankView",
		"PersonalHeadChooseView",
		"HeadFrame3058",
		"WaterRankView",
		-- "MonopolyRankView",
		--"MonopolyRankRuleView",
		--"MessageBox",
		--"RewardsView",
		"WaterRankHelpView",
	},
	temp_V82 = {
		"BatteryGiftView",
		"Battery_1138",
		"Battery_1136",
		"Battery_1129",
		"Battery_1123",
		"Battery_1110",
		"GuideView",
		"MonopolyRankView",
		"MonopolyRankRuleView",
		"ActivityCollectionView",
	},
	temp_V84 = {
		"RewardsView",
	},
	temp_V85 = {
		-- "MonthRebateView",
		-- "HallView",
	},
	temp_V86 = {
		--"LoginView",
	},
	temp_V87 = {
		"HallView",
		"HeadFrame9100",
	},
	temp_V88 = {
		"MarsTaskView",
		"MarsTaskStoryView"
	},
	temp_V89 = {
		"MessageBox",
		"MonthRebateView",
		"Act_UserAgreement",
		"TotalTipsView",
	},
	temp_Portrait = {
		"FundViewPortrait",
		"PortraitTestView",
		"PersonalInfoViewPortrait",
		"GNode",
		"BenefitsViewPortrait",
		"CashCowView",
		"CashCowViewPortrait",
		"SetUpSoundViewPortrait",
		"WalletView",
		"StoreViewPortrait",
		"GameExitTipViewPortrait",
		"SelectGiftCollectionViewPortrait",
		"NoviceGiftViewPortrait",
		"FreeChipsCollectionViewPortrait",
		"DailyGiftCollectionViewPortrait",
		"TipPortrait",
	},
}

for abName, imageList in pairs(ImageDefine) do
	for _, image in pairs(imageList) do
		if ResourceDefine.Image[image] then
			logError("Image:"..image.."重复！！！");
		end
		ResourceDefine.Image[image] = abName
		ResourceDefine.Image[image .. ".png"] = abName
	end
end

for abName, soundList in pairs(SoundDefine) do
	for _, sound in pairs(soundList) do
		if ResourceDefine.Sound[sound] then
			logError("Sound:"..sound.."重复！！！");
		end
		ResourceDefine.Sound[sound] = abName
		ResourceDefine.Sound[sound .. ".ogg"] = abName
	end
end

for abName, prefabList in pairs(PrefabDefine) do
	for _, prefab in pairs(prefabList) do
		if ResourceDefine.Prefab[prefab] then
			logError("Prefab:"..prefab.."重复！！！");
		end
		ResourceDefine.Prefab[prefab] = abName
		ResourceDefine.Prefab[prefab .. ".prefab"] = abName
	end
end

return ResourceDefine
