-- ************************************************************
-- @File: ViewCenter.lua View及对应的文件路径
-- @Summary1:不要轻易修改 View2FilePath 里面的 Key 的名称,因为 ViewDefine.lua 已经把 Key 当成枚举了，可以 CC.ViewDefine.LoadingView 使用
-- @Summary2:如果因为拼写错误,或者其他原因要修改 Key 的,请复制多一行进行修改，不要修改原来的
-- @Summary3:如果修改了原先的,子游戏内如果用到该 View (例如 CC.ViewDefine.LoadingView )修改后,会找不到原来的
-- @Version: 1.0
-- @Author: luogizz
-- @Date: 2023-04-26 16:29:16
-- ************************************************************
local ViewCenter = {}

local View2FilePath = {
	LoadingView = "View/OtherView/LoadingView",
	LoginView = "View/LoginView/LoginView",
	GuideView = "View/GuideView/GuideView",
	DownloadView = "View/DownloadView/DownloadView",
	SlotGuideView = "View/SlotGuideView/SlotGuideView",
	SlotGuideExView = "View/SlotGuideView/SlotGuideExView",
	HallView = "View/HallView/HallView",
	GameList = "View/HallView/GameList",
	PopupView = "View/HallView/PopupView",
	SelectionGameView = "View/SelectionGameView/SelectionGameView",
	ArenaView = "View/ArenaView/ArenaView",
	ThirdGameTipView = "View/ThirdGameTipView/ThirdGameTipView",
	WarningTipView = "View/WarningTipView/WarningTipView",
	AdvertiseView = "View/AdvertiseView/AdvertiseView",
	OnlineAward = "View/OnlineAward/OnlineAward",
	OnlineIcon = "View/OnlineIcon/OnlineIcon",
	SlotsOnlineIcon = "View/OnlineIcon/SlotsOnlineIcon",
	NoviceIcon = "SubGame/NoviceIcon",
	ShakeIcon = "SubGame/ShakeIcon",
	LimmitAwardView = "View/OnlineAward/LimmitAwardView",
	OnlineLottery = "View/OnlineLottery/OnlineLottery",
	PersonalInfoView = "View/PersonalInfoView/PersonalInfoView",
	RenameView = "View/PersonalInfoView/RenameView",
	ReBirthdayView = "View/PersonalInfoView/ReBirthdayView",
	VerifiedView = "View/PersonalInfoView/VerifiedView",
	UnbindTelView = "View/PersonalInfoView/UnbindTelView",
	HeadIcon = "View/PersonalInfoView/HeadIcon",
	ChipCounter = "View/PersonalInfoView/ChipCounter",
	DiamondCounter = "View/PersonalInfoView/DiamondCounter",
	VIPCounter = "View/PersonalInfoView/VIPCounter",
	IntegralCounter = "View/PersonalInfoView/IntegralCounter",
	RoomcardCounter = "View/PersonalInfoView/RoomcardCounter",
	PersonalBindPhoneView = "View/PersonalInfoView/PersonalBindPhoneView",
	PersonalHeadChooseView = "View/PersonalInfoView/PersonalHeadChooseView",
	UnLockVipView = "View/PersonalInfoView/UnLockVipView",
	VipUpgradeView = "View/PersonalInfoView/VipUpgradeView",
	SetSexView = "View/PersonalInfoView/SetSexView",
	OtherPlayerInfoView = "View/OtherPlayerInfoView/OtherPlayerInfoView",
	BackpackView = "View/BackpackView/BackpackView",
	BackUseView = "View/BackpackView/BackUseView",
	BackJumpView = "View/BackpackView/BackJumpView",
	PackbackItemDes = "View/BackpackView/PackbackItemDes",
	BeforeSendTipsView = "View/GiveGiftSearchView/BeforeSendTipsView",
	GiveGiftSearchView = "View/GiveGiftSearchView/GiveGiftSearchView",
	GiftRankView = "View/GiveGiftSearchView/GiftRankView",
	GiveChangeSelfView = "View/GiveGiftSearchView/GiveChangeSelfView",
	RealStoreIcon = "View/RealStoreView/RealStoreIcon",
	RealStoreExplainView = "View/RealStoreView/RealStoreExplainView",
	TreasureView = "View/TreasureView/TreasureView",
	AgentExView = "View/TreasureView/AgentExView",
	TreasureInformation = "View/TreasureView/TreasureInformation",
	TreasureCodePanel = "View/TreasureView/TreasureCodePanel",
	TreasureRecordPanel = "View/TreasureView/TreasureRecordPanel",
	TreasureTips = "View/TreasureView/TreasureTips",
	CardFragExchangeView = "View/TreasureView/CardFragExchangeView",
	TreasureTipsView = "View/TreasureView/TreasureTipsView",
	SuperTreasureView = "View/SuperTreasureView/SuperTreasureView",
	TreasureExchangeTips = "View/TreasureView/TreasureExchangeTips",
	TreasureNotEnoughTips = "View/TreasureView/TreasureNotEnoughTips",
	ChipNotEnoughTips = "View/TreasureView/ChipNotEnoughTips",
	WaterSprinklingView = "View/WaterSprinkling/WaterSprinklingView",
	StoreView = "View/StoreView/StoreView",
	StoreExplainView = "View/StoreView/StoreExplainView",
	SendChipsExplainView = "View/SendChipsView/SendChipsExplainView",
	StoreInputBoxView = "View/StoreView/StoreInputBoxView",
	WebPayView = "View/StoreView/WebPayView",
	ActiveView = "View/ActiveView/ActiveView",
	RewardNoticeView = "View/RewardNoticeView/RewardNoticeView",
	MailView = "View/MailView/MailView",
	FriendView = "View/FriendView/FriendView",
	ViolentAttackView = "View/ViolentAttackView/ViolentAttackView",
	SetUpView = "View/SetUpView/SetUpView",
	SetUpPolicyView = "View/SetUpView/SetUpPolicyView",
	SetUpSoundView = "View/SetUpView/SetUpSoundView",
	SetUpServiceView = "View/SetUpView/SetUpServiceView",
	SetUpLogoutView = "View/SetUpView/SetUpLogoutView",
	ChatPanel = "View/ChatPanel/ChatPanel",
	NoticeBord = "View/ChatPanel/NoticeBord",
	SpeakerBord = "View/ChatPanel/SpeakerBord",
	RankCollectionView = "View/RankCollectionView/RankCollectionView",
	RankingListView = "View/RankingListView/RankingListView",
	WeekRankView = "View/WeekRankView/WeekRankView",
	SongkranRankView = "View/SongkranRankView/SongkranRankView",
	MonthRankView = "View/MonthRankView/MonthRankView",
	MonthRankRuleView = "View/MonthRankView/MonthRankRuleView",
	RankIcon = "View/MonthRankView/RankIcon",
	NoticeView = "View/NoticeView/NoticeView",
	ActiveRankView = "View/ActiveRankView/ActiveRankView",
	NoviceGiftView = "View/NoviceGiftView/NoviceGiftView",
	SelectActiveView = "View/SelectActiveView/SelectActiveView",
	SendChipsView = "View/SendChipsView/SendChipsView",
	SendChipsTipsView = "View/SendChipsView/SendChipsTipsView",
	SendAntifraudView = "View/SendChipsView/SendAntifraudView",
	AchievementGiftMainView = "View/AchievementGift/AchievementGiftMainView",
	AchievementGiftView = "View/AchievementGift/AchievementGiftView",
	MessageBox = "View/OtherView/MessageBox",
	MessageBoxExtend = "View/OtherView/MessageBoxExtend",
	MessageBoxNewStyle = "View/OtherView/MessageBoxNewStyle",
	VipView = "View/OtherView/VipView",
	BenefitsView = "View/OtherView/BenefitsView",
	ConnectingView = "View/OtherView/ConnectingView",
	Tip = "View/OtherView/Tip",
	InviteTip = "View/OtherView/InviteTip",
	DebugView = "View/OtherView/DebugView",
	PortraitTestView = "View/OtherView/PortraitTestView",
	LoginAwardView = "View/OtherView/LoginAwardView",
	RewardsView = "View/RewardsView/RewardsView",
	FundView = "View/FundView/FundView",
	FortunebagView = "View/FortunebagView/FortunebagView",
	AgentView = "View/Agent/AgentView",
	AgentEarningsView = "View/Agent/AgentEarningsView",
	AgentGeneralizeView = "View/Agent/AgentGeneralizeView",
	AgentJuniorView = "View/Agent/AgentJuniorView",
	AgentRuleView = "View/Agent/AgentRuleView",
	AgentShareView = "View/Agent/AgentShareView",
	AgentTaskView = "View/Agent/AgentTaskView",
	AgentUnderlingView = "View/Agent/AgentUnderlingView",
	AgentNewView = "View/Agent/AgentNewView",
	AgentInvitationView = "View/Agent/AgentInvitationView",
	AgentProxy = "View/Agent/AgentProxy",
	AgentRevenueView = "View/Agent/AgentRevenueView",
	AgentMyGrades = "View/Agent/AgentMyGrades",
	AgentRank = "View/Agent/AgentRank",
	BlessLotteryView = "View/BlessLotteryView/BlessLotteryView",
	BlessSearchView = "View/BlessLotteryView/BlessSearchView",
	GameEffectView = "SubGame/GameEffectView",
	LotteryView = "View/LotteryView/LotteryView",
	LotteryRuleView = "View/LotteryView/LotteryRuleView",
	MyPurchaseNumView = "View/LotteryView/MyPurchaseNumView",
	PastLotteryView = "View/LotteryView/PastLotteryView",
	PurchaseRecordView = "View/LotteryView/PurchaseRecordView",
	SplashingView = "View/SplashingView/SplashingView",
	SplashingSearchView = "View/SplashingSearchView/SplashingSearchView",
	BetDetailView = "View/LotteryView/BetDetailView",
	LotteryRankView = "View/LotteryView/LotteryRankView",
	ShakeView = "View/ShakeView/ShakeView",
	ShakeExplainView = "View/ShakeView/ShakeExplainView",
	ShakeRankView = "View/ShakeView/ShakeRankView",
	SignInView = "View/SignInView/SignInView",
	SignExplainView = "View/SignInView/SignExplainView",
	SignWinView = "View/SignInView/SignWinView",
	SignZhuan = "View/SignInView/SignZhuan",
	InformationView = "View/InformationView/InformationView",
	DailyTurntableView = "View/DailyTurntableView/DailyTurntableView",
	TurntableRewardView = "View/DailyTurntableView/TurntableRewardView",
	TurntableRechargeView = "View/DailyTurntableView/TurntableRechargeView",
	NumberRoller = "View/OtherView/NumberRoller",
	FreeChipsCollectionView = "View/FreeChipsCollectionView/FreeChipsCollectionView",
	FreeChipsIcon = "View/FreeChipsCollectionView/FreeChipsIcon",
	SlotFreeChipsIcon = "View/FreeChipsCollectionView/SlotFreeChipsIcon",
	SelectGiftCollectionView = "View/SelectGiftCollectionView/SelectGiftCollectionView",
	SelectGiftIcon = "View/SelectGiftCollectionView/SelectGiftIcon",
	SlotSelectGiftIcon = "View/SelectGiftCollectionView/SlotSelectGiftIcon",
	SelectGiftIconWithoutDailyGift = "View/SelectGiftCollectionView/SelectGiftIconWithoutDailyGift",
	LoyKraThong = "View/LoyKraThong/LoyKraThong",
	ElephantIcon = "View/GoldenElephant/ElephantIcon",
	GoldenElephant = "View/GoldenElephant/GoldenElephant",
	ElephantExplainView = "View/GoldenElephant/ElephantExplainView",
	LuckyTurntableView = "View/LuckyTurntableView/LuckyTurntableView",
	WalletView = "View/WalletView/WalletView",
	TreasureBoxGiftView = "View/TreasureBoxGiftView/TreasureBoxGiftView",
	DailyGiftCollectionView = "View/DailyGiftCollectionView/DailyGiftCollectionView",
	DailyGiftIcon = "View/DailyGiftCollectionView/DailyGiftIcon",
	DailyGiftBuyu = "View/DailyGiftCollectionView/DailyGiftBuyu",
	DailyGiftFourBuyu = "View/DailyGiftCollectionView/DailyGiftFourBuyu",
	DailyGiftDummy = "View/DailyGiftCollectionView/DailyGiftDummy",
	DailyGiftPokdeng = "View/DailyGiftCollectionView/DailyGiftPokdeng",
	DailyDealsView = "View/DailyDealsView/DailyDealsView",
	BrokeGiftView = "View/BrokeGiftView/BrokeGiftView",
	BrokeBigGiftView = "View/BrokeGiftView/BrokeBigGiftView",
	SlotBrokeGiftIcon = "View/SelectGiftCollectionView/SlotBrokeGiftIcon",
	DailyGiftAirplane = "View/DailyGiftCollectionView/DailyGiftAirplane",
	VipThreeCardView = "View/VipThreeCardView/VipThreeCardView",
	NewbieTaskView = "View/NewbieTaskView/NewbieTaskView",
	FragmentTaskView = "View/FragmentTaskView/FragmentTaskView",
	AirplaneUnlockGiftView = "View/AirplaneUnlockGiftView/AirplaneUnlockGiftView",
	PirateTreasureGiftView = "View/PirateTreasureGiftView/PirateTreasureGiftView",
	ActivityCollectionView = "View/ActivityCollectionView/ActivityCollectionView",
	MidActiveIcon = "View/ActivityCollectionView/MidActiveIcon",
	CommonExplainView = "View/OtherView/CommonExplainView",
	CommonItemDes = "View/OtherView/CommonItemDes",
	ActSignInView = "View/ActSignInView/ActSignInView",
	ActSignInBox = "View/ActSignInView/ActSignInBox",
	NoviceSignInView = "View/NoviceSignInView/NoviceSignInView",
	FlyCoin = "View/FlyCoin",
	CaptureScreenShareView = "View/ShareView/CaptureScreenShareView",
	ImageShareView = "View/ShareView/ImageShareView",
	DailyLotteryShareView = "View/ShareView/DailyLotteryShareView",
	CapsuleView = "View/CapsuleView/CapsuleView",
	ComposeCapsuleView = "View/CapsuleView/ComposeCapsuleView",
	GiftSignInView = "View/GiftSignInView/GiftSignInView",
	ExitToGuideView = "View/ExitToGuideView/ExitToGuideView",
	GuideToGameView = "View/GuideToGameView/GuideToGameView",
	----------------------------suprise------
	Act_EveryGift = "View/ActiveView/Act_EveryGift",
	Act_Facebook = "View/ActiveView/Act_Facebook",
	Act_Line = "View/ActiveView/Act_Line",
	Act_proxy = "View/ActiveView/Act_proxy",
	Act_SendTutorial = "View/ActiveView/Act_SendTutorial",
	Act_Service = "View/ActiveView/Act_Service",
	Act_CDKey = "View/ActiveView/Act_CDKey",
	Act_Clause = "View/ActiveView/Act_Clause",
	Act_Notice = "View/ActiveView/Act_Notice",
	Act_SetUpPolicy = "View/ActiveView/Act_SetUpPolicy",
	Act_RelieveLine = "View/ActiveView/Act_RelieveLine",
	Act_Rank = "View/ActiveView/Act_Rank",
	Act_FraudNotice = "View/ActiveView/Act_FraudNotice",
	Act_GoToFacebook = "View/ActiveView/Act_GoToFacebook",
	Act_NewFraudNotice = "View/ActiveView/Act_NewFraudNotice",
	Act_NewCDKey = "View/ActiveView/Act_NewCDKey",
	Act_FBChatGroup = "View/ActiveView/Act_FBChatGroup",
	Act_UserAgreement = "View/ActiveView/Act_UserAgreement",
	-- 小厅
	MiniGameMainView = "View/MiniGame/MiniGameMainView",
	ActiveEntryIcon = "View/ActiveEntryView/ActiveEntryIcon",
	ActiveEntryView = "View/ActiveEntryView/ActiveEntryView",
	ActiveShareBoard = "View/ActiveEntryView/ActiveShareBoard",
	--------------------提审专用---------------
	TrailAndroidGameList = "View/TrailView/TrailAndroidGameList",
	TrailAndroidHallView = "View/TrailView/TrailAndroidHallView", --Android大厅
	TrailIOSGameList = "View/TrailView/TrailIOSGameList",
	TrailIOSHallView = "View/TrailView/TrailIOSHallView", --IOS大厅
	TrailStoreView = "View/TrailView/TrailStoreView",
	TrailStorePropView = "View/TrailView/TrailStoreView", --喇叭商店
	TrailPersonalInfoView = "View/TrailView/TrailPersonalInfoView",
	TrailLoginView = "View/TrailView/TrailLoginView",
	TrailIOSLoginView = "View/TrailView/TrailIOSLoginView",
	TrailIOSSetUpSoundView = "View/TrailIOSSetUpSoundView/TrailIOSSetUpSoundView",
	GameExitTipView = "View/GameExitTipView/GameExitTipView",
	-- 每日抽奖界面
	DailyLotteryView = "View/DailyLotteryView/DailyLotteryView",
	DailyLotteryRuleView = "View/DailyLotteryView/DailyLotteryRuleView",
	DailyLotteryTaskGuideView = "View/DailyLotteryView/DailyLotteryTaskGuideView",
	PackageTestView = "View/PackageTestView/PackageTestView",
	---------------------Slot限时比赛---------------------
	Slot_MatchGiftIcon = "View/SlotMatch/Slot_MatchGiftIcon",
	Slot_MatchHistoryRankIcon = "View/SlotMatch/Slot_MatchHistoryRankIcon",
	Slot_MatchPrepareView = "View/SlotMatch/Slot_MatchPrepareView",
	Slot_MatchRewardRankView = "View/SlotMatch/Slot_MatchRewardRankView",
	Slot_MatchHelpView = "View/SlotMatch/Slot_MatchHelpView",
	Slot_MatchHistoryRankView = "View/SlotMatch/Slot_MatchHistoryRankView",
	Slot_MatchDoingView = "View/SlotMatch/Slot_MatchDoingView",
	Slot_MatchSettlementView = "View/SlotMatch/Slot_MatchSettlementView",
	Slot_MatchGiftView = "View/SlotMatch/Slot_MatchGiftView",
	Slot_MatchTipsView = "View/SlotMatch/Slot_MatchTipsView",
	Slot_MatchRewardsView = "View/SlotMatch/Slot_MatchRewardsView",
	Slot_MatchRealRankView = "View/SlotMatch/Slot_MatchRealRankView",
	SlotCommonNoticeIcon = "View/SlotCommonNoticeView/SlotCommonNoticeIcon",
	SlotCommonNoticeView = "View/SlotCommonNoticeView/SlotCommonNoticeView",
	DisScreenShotShareView = "View/ShareView/DisScreenShotShareView",
	--假日特惠
	HolidayDiscountsView = "View/HolidayDiscountsView/HolidayDiscountsView",
	BroadCast = "View/HolidayDiscountsView/BroadCast",
	-- 摇钱树
	CashCowView = "View/CashCowView/CashCowView",
	CashCowIcon = "View/CashCowView/CashCowIcon",
	--超级夺宝奖券兑换
	GiftExchangeView = "View/GiftExchangeView/GiftExchangeView",
	GiftTurntableView = "View/GiftTurntableView/GiftTurntableView",
	--10首冲礼包
	FirstBuyGiftView = "View/FirstBuyGiftView/FirstBuyGiftView",
	--10+29碎片礼包
	DebrisGiftView = "View/DebrisGiftView/DebrisGiftView",
	--地鼠每日礼包
	DailyGiftDiglett = "View/DailyGiftCollectionView/DailyGiftDiglett",
	--地鼠大乱斗
	DailyGiftPharaoh = "View/DailyGiftCollectionView/DailyGiftPharaoh",
	--僵尸礼包
	DailyGiftZombie = "View/DailyGiftCollectionView/DailyGiftZombie",
	DailyGiftBull = "View/DailyGiftCollectionView/DailyGiftBull",
	ZombieUnLockGiftView = "View/ZombieUnLockGiftView/ZombieUnLockGiftView",
	--龙转盘
	DragonTurntableView = "View/DragonTurntableView/DragonTurntableView",
	--飞机幸运转盘
	AirplaneTurntableView = "View/AirplaneTurntableView/AirplaneTurntableView",
	FortuneCatView = "View/FortuneCatView/FortuneCatView",
	PayGiftView = "View/PayGiftView/PayGiftView",
	DiffRankIcon = "View/PayGiftView/DiffRankIcon",
	PayGiftExplainView = "View/PayGiftView/PayGiftExplainView",
	ElkLimitGiftView = "View/ElkLimitGiftView/ElkLimitGiftView",
	ChristmasTaskView = "View/ChristmasTaskView/ChristmasTaskView",
	SpecialRewardsView = "View/RewardsView/SpecialRewardsView",
	VipRightsGiftView = "View/VipRightsGiftView/VipRightsGiftView",
	CrystalStoreView = "View/CrystalStoreView/CrystalStoreView",
	BatteryLotteryView = "View/BatteryLotteryView/BatteryLotteryView",
	BatteryExchangeShop = "View/BatteryExchangeShop/BatteryExchangeShop",
	Marquee = "View/BatteryLotteryView/Marquee",
	CompoundPanel = "View/BatteryLotteryView/CompoundPanel",
	CompositeView = "View/CompositeView/CompositeView",
	CompositeJP = "View/CompositeView/CompositeJP",
	CompositeGiftView = "View/CompositeGiftView/CompositeGiftView",
	--生日礼包
	BirthdayAwardView = "View/BirthdayView/BirthdayAwardView",
	BirthdayView = "View/BirthdayView/BirthdayView",
	SendSetView = "View/SendChipsView/SendSetView",
	NewPayGiftView = "View/NewPayGiftView/NewPayGiftView",
	NewPayGiftPreviewView = "View/NewPayGiftView/NewPayGiftPreviewView",
	HCoinView = "View/HCoinView/HCoinView",
	FootballView = "View/FootballView/FootballView",
	SubscribeView = "View/SubscribeView/SubscribeView",
	QueueView = "View/QueueView/QueueView",
	GetTicketView = "View/GetTicketView/GetTicketView",
	NewElkLimitGiftView = "View/NewElkLimitGiftView/NewElkLimitGiftView",
	InviteLotteryView = "View/InviteLotteryView/InviteLotteryView",
	GobackRewardView = "View/GobackRewardView/GobackRewardView",
	PropSentView = "View/BackpackView/PropSentView",
	--周年庆转盘
	AnniversaryTurntableView = "View/AnniversaryTurntableView/AnniversaryTurntableView",
	AnniversaryRewardsView = "View/AnniversaryTurntableView/AnniversaryRewardsView",
	AnniversaryRankView = "View/AnniversaryRankView/AnniversaryRankView",
	CelebrationView = "View/CelebrationView/CelebrationView",
	CelebrationFrameView = "View/CelebrationView/CelebrationFrameView",
	CelebrationTipView = "View/CelebrationView/CelebrationTipView",
	LoginQueueView = "View/LoginQueueView/LoginQueueView", --登录排队
	ThirdPartyView = "View/ThirdPartyView/ThirdPartyView",
	DonateView = "View/DonateView/DonateView", --功德捐献
	GameTipView = "View/GameTipView/GameTipView",
	WaterRankView = "View/WaterRankView/WaterRankView",
	WaterRankHelpView = "View/WaterRankView/WaterRankHelpView",
	GoldOwnerView = "View/AnniversaryTurntableView/GoldOwnerView",
	MonthCardView = "View/MonthCardView/MonthCardView", --月卡
	MonthCardPriviView = "View/MonthCardView/MonthCardPriviView", --月卡特权
	SpecialRewardView = "View/MonthCardView/SpecialRewardView", --奖励弹框
	VerSafePassWordView = "View/SafeBoxView/VerSafePassWordView",
	SetSafePassWordView = "View/SafeBoxView/SetSafePassWordView",
	SafeBoxView = "View/SafeBoxView/SafeBoxView",
	BindTelView = "View/SafeBoxView/BindTelView",
	SafeBoxGuideView = "View/SafeBoxView/SafeBoxGuideView",
	ForGetPassWordView = "View/SafeBoxView/ForGetPassWordView",
	SafePassWordExplainView = "View/SafeBoxView/SafePassWordExplainView",
	SafetyCompleteView = "View/SafetyCompleteView/SafetyCompleteView",
	NumberRollerEx = "View/OtherView/NumberRollerEx", --数字滚动
	HalloweenView = "View/HalloweenView/HalloweenView",
	HalloweenLoginGiftView = "View/HalloweenLoginGiftView/HalloweenLoginGiftView",
	--万圣节登陆好礼
	IdentityVerificationView = "View/IdentityVerificationView/IdentityVerificationView",
	--银行渠道实名验证
	TotalWaterRankView = "View/TotalWaterRankView/TotalWaterRankView",
	StarRatingView = "View/StarRatingView/StarRatingView",
	--五星好评
	HolidayTaskView = "View/HolidayTaskView/HolidayTaskView",
	--节日任务（2022泼水节沙塔）
	HolidayTaskExplainView = "View/HolidayTaskView/HolidayTaskExplainView",
	UnlockGiftView = "View/HolidayTaskView/UnlockGiftView",
	SpecialOfferGiftView = "View/SpecialOfferGiftView/SpecialOfferGiftView",
	--"特价礼包（2022泼水节）"
	--火星任务
	MarsTaskView = "View/MarsTaskView/MarsTaskView",
	MarsTaskIcon = "View/MarsTaskView/MarsTaskIcon",
	MarsTaskAtlasView = "View/MarsTaskAtlasView/MarsTaskAtlasView",
	MarsTaskStoryView = "View/MarsTaskStoryView/MarsTaskStoryView",
	MarsTaskUnlockView = "View/MarsTaskView/MarsTaskUnlockView",
	MarsTaskRewardsView = "View/MarsTaskView/MarsTaskRewardsView",
	MarsTaskEntryView = "View/MarsTaskView/MarsTaskEntryView",
	--vip细化礼包
	VIPBestGfitView = "View/VIPBestGfitView/VIPBestGfitView",
	--通用节日促销礼包
	CommonHolidayGiftView = "View/CommonHolidayGiftView/CommonHolidayGiftView",
	AutoScroll = "View/AutoScroll/AutoScroll",
	--炮台排行榜
	BatteryRankView = "View/BatteryRankView/BatteryRankView",
	BatteryPossessView = "View/BatteryRankView/BatteryPossessView",
	BatteryBookView = "View/BatteryRankView/BatteryBookView",
	BatteryEntryeffect = "View/BatteryRankView/BatteryEntryeffect",
	JackpotRoller = "View/OtherView/JackpotRoller",
	--世界杯相关
	WorldCupView = "View/WorldCupView/WorldCupView",
	WorldCupMainView = "View/WorldCupView/WorldCupMainView",
	ScheduleBoard = "View/WorldCupView/ScheduleBoard",
	WorldCupGiftView = "View/WorldCupView/WorldCupGiftView",
	WorldCupRankView = "View/WorldCupView/WorldCupRankView",
	WorldCupADPageView = "View/WorldCupView/WorldCupADPageView",
	WorldCupMascot = "View/WorldCupView/WorldCupMascot",
	WorldCupBetView = "View/WorldCupView/WorldCupBetView",
	WorldCupMatchView = "View/WorldCupView/WorldCupMatchView",
	WorldCupGuessView = "View/WorldCupView/WorldCupGuessView",
	WorldCupTipsView = "View/WorldCupView/WorldCupTipsView",
	WorldCupRecordView = "View/WorldCupView/WorldCupRecordView",
	--流水任务
	FlowWaterTaskView = "View/FlowWaterTaskView/FlowWaterTaskView",
	--特惠每日礼包
	SuperDailyGiftView = "View/SuperDailyGiftView/SuperDailyGiftView",
	WebServiceView = "View/SetUpView/WebServiceView",
	CommonWebView = "View/CommonWebView/CommonWebView",
	--大富翁
	MonopolyView = "View/MonopolyView/MonopolyView",
	MonopolyRuleView = "View/MonopolyView/MonopolyRuleView",
	WaterIcon = "View/IconView/WaterIcon",
	MonopolyGiftView = "View/MonopolyView/MonopolyGiftView",
	--大富翁排行榜
	MonopolyRankView = "View/MonopolyRankView/MonopolyRankView",
	MonopolyRankRuleView = "View/MonopolyRankView/MonopolyRankRuleView",
	BatteryGiftView = "View/BatteryGiftView/BatteryGiftView",
	--月度返利
	MonthRebateView = "View/MonthRebateView/MonthRebateView",
	TotalTipsView = "View/TotalTipsView/TotalTipsView"
}

ViewCenter.View2FilePath = View2FilePath
-- for viewName, viewPath in pairs(ViewCenter.View2FilePath) do
-- 	ViewCenter[viewName] = require(viewPath);
-- end

local map = {}

setmetatable(
	ViewCenter,
	{
		__index = function(_, viewName)
			if not map[viewName] and View2FilePath[viewName] then
				map[viewName] = require(View2FilePath[viewName])
			end
			return map[viewName]
		end
	}
)

return ViewCenter
