local lan =
{
    seasonIdx = '(%d)',
    dayPool = '每日奖池',
    seasonPool = '赛季奖池',
    pack = '我的卡包',
    market = '市场',
	Orepool = '我的宝箱',
    dayRecord = '每日记录',
    todayPool = '今日奖池',
    curAllPower = '当前全服算力：',
    rank = '排名',
    noRank = '未上榜',
	nick = '昵称',
	power = '算力',
	power_ = '算力：',
	grade = '品质',
	reward = '奖金',
	rewardFRT = '奖品',
	rankMine = '我的排名：',
	powerMine = '我的算力：',
	rewardMine = '预计奖金：',
	getReward = '领取奖金',
	getDayPoolReward = '获得金币奖励%d',
	getSeasonPoolReward = '获得金币奖励%d, FRT奖励%d',
	noReward = '暂无可领取的奖励',
	noRewardBtn = '不可领取',
	getRewardBtn = '领取',
	seasonRecord = '赛季记录',
    totalPool = '总奖池：',
	
	selfPower = '总算力：',
	composePower = '合成后算力：',
	oneKey = '批量放入',
	compose = '合成',
	arm = '装备',
	armed = '装备中',
	composed = '合成中',
	unArm = '卸下',
	enhance = '洗练',
	enhanceSuccess = '洗练成功',
	enhanceEffect = '洗练效果',
	need5 = '合成需要5张同品质NFT卡',
	maxGrade = '已经是最高品质',
	getCard = '恭喜获得',
	dragToArm = '请拖拽装备',
	
	sure = '确认',
	cancel = '取消',
	buyConfirm = '是否使用%d个FRT购买此商品',
	
	price = '售价',
	buy = '购买',
	cardDelTip = '赛季结束后，所有图卡将被系统回收',
	refresh = '刷新',
	allCard = '全部图卡',
	gradeCard = '%d星图卡',
	sellCard = '寄售图卡',
	sellRecord = '售卖记录',
	selling = '当前寄售',
	sureSell = '确认寄售',
	inputprice = '输入FRT金额',
	cancelSell = '取消寄售',
	curPerform = '目前输入性价比：%.2f%%',
	reqSellSuccess = '上架成功',
	reqFailed = '请求失败',
	noSelectCard = '请先选择要上架的图卡',
	armedCannotSell = '不能上架已装备的图卡',
	illegalPrice = '非法的价格',
	touchTip = '点击任意地方关闭界面',
	tradeTax = '每次成功交易，将抽取%.1f%%FRT币作为手续费',
	tradeFree = '本赛季交易免收手续费',
	appFRT = '我的钱包',
	
	modifyPwd = '修改登录密码',
	modifyTip = 'FRT账户信息修改',
	modifySure = '确认修改',
	pwdRule = '密码只能输入6-20个字母、数字、下划线',
	operateSuccess = '操作成功',
	noSellBinding = '不能出售绑定图卡',
	hintBinding = "本次合成使用了“<color=#DC143C>不可交易</color>”图卡，合成后的图卡也将变为“<color=#DC143C>不可交易</color>”，请问是否确认继续？",
	dayGetCardHint = "每日登录系统，即赠送免费算力图卡",
	noSell = "不可交易",
	-- = '',
	-- = '',
	nftGoldChest = "<color=#E1AB38>黄金宝箱：</color><color=#778CAB>打开后，随机获得大量FRT币奖励。</color>",
	nftSilverChest = "<color=#46B7DC>白银宝箱：</color><color=#778CAB>打开后，随机获得中量FRT币奖励。</color>",
	nftBronzeChest = "<color=#D26523>青铜宝箱：</color><color=#778CAB>打开后，随机获得少量FRT币奖励。</color>",

	pleasedevelopment = "敬请期待....",
	chestTpyeText = {
		[1] = "黄金宝箱",
		[2] = "白银宝箱",
		[3] = "青铜宝箱",
	},
	chestText = {
		[1] = "每个黄金宝箱，可随机获得%.6f ~ %.6f个FRT币",
		[2] = "每个白银宝箱，可随机获得%.6f ~ %.6f个FRT币",
		[3] = "每个青铜宝箱，可随机获得%.6f ~ %.6f个FRT币",
	},
	NFTOrepool = 'NFT宝箱',
	orepoolInsufficientQuantity = "您没有足够的箱子",
	openboxOne = '打开',
	openboxOTen = '打开%d个',
	chestSum = '<color=#778CAB>库存：</color>%d个'

}

return lan
